Repository felangel/bloc, pull requests merged in 2019-03, with the labels that each got.

#128 Vscode extension enhancement
  extensions/vscode/.gitignore
  extensions/vscode/.vscodeignore
  extensions/vscode/CHANGELOG.md
  extensions/vscode/README.md
  extensions/vscode/package-lock.json
  extensions/vscode/package.json
  extensions/vscode/src/extension.ts
  extensions/vscode/src/templates/barrel.template.ts
  extensions/vscode/src/templates/bloc-event.template.ts
  extensions/vscode/src/templates/bloc-state.template.ts
  extensions/vscode/src/templates/bloc.template.ts
  extensions/vscode/src/templates/index.ts
  extensions/vscode/src/test/extension.test.ts
  extensions/vscode/src/test/index.ts
  extensions/vscode/tsconfig.json
  extensions/vscode/tslint.json
Labels: enhancement

#129 bloc v0.9.4
  packages/bloc/CHANGELOG.md
  packages/bloc/lib/src/bloc.dart
  packages/bloc/pubspec.yaml
  packages/bloc/test/bloc_test.dart
  packages/bloc/test/helpers/counter/counter_bloc.dart
Labels: enhancement

#135 Removes Settings Widget
  docs/flutterweathertutorial.md
Labels: documentation

#141 Add Flutter Todos Tutorial
  docs/_sidebar.md
  docs/fluttertodostutorial.md
  examples/flutter_todos/lib/blocs/blocs.dart
  examples/flutter_todos/lib/blocs/filtered_todos/filtered_todos_bloc.dart
  examples/flutter_todos/lib/blocs/filtered_todos/filtered_todos_event.dart
  examples/flutter_todos/lib/blocs/filtered_todos/filtered_todos_state.dart
  examples/flutter_todos/lib/blocs/stats/stats.dart
  examples/flutter_todos/lib/blocs/stats/stats_bloc.dart
  examples/flutter_todos/lib/blocs/stats/stats_event.dart
  examples/flutter_todos/lib/blocs/stats/stats_state.dart
  examples/flutter_todos/lib/blocs/tab/tab.dart
  examples/flutter_todos/lib/blocs/tab/tab_event.dart
  examples/flutter_todos/lib/blocs/todos/todos.dart
  examples/flutter_todos/lib/blocs/todos/todos_event.dart
  examples/flutter_todos/lib/blocs/todos/todos_state.dart
  examples/flutter_todos/lib/main.dart
  examples/flutter_todos/lib/models/todo.dart
  examples/flutter_todos/lib/screens/home_screen.dart
  examples/flutter_todos/lib/widgets/filter_button.dart
  examples/flutter_todos/lib/widgets/filtered_todos.dart
  examples/flutter_todos/lib/widgets/stats.dart
  packages/angular_bloc/pubspec.yaml
Labels: documentation, example

#148 Added IntelliJ Bloc generator
  extensions/intellij/intellij_generator_plugin/.gitignore
  extensions/intellij/intellij_generator_plugin/build.gradle
  extensions/intellij/intellij_generator_plugin/gradle.properties
  extensions/intellij/intellij_generator_plugin/gradlew
  extensions/intellij/intellij_generator_plugin/gradlew.bat
  extensions/intellij/intellij_generator_plugin/settings.gradle
  extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/action/GenerateBlocAction.kt
  extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/action/GenerateBlocDialog.form
  extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/action/GenerateBlocDialog.java
  extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/generator/BlocGeneratorFactory.kt
  extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/generator/Generator.kt
  extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/generator/components/BlocEventGenerator.kt
  extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/generator/components/BlocExportsGenerator.kt
  extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/generator/components/BlocGenerator.kt
  extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/generator/components/BlocStateGenerator.kt
  extensions/intellij/intellij_generator_plugin/src/main/resources/META-INF/plugin.xml
  extensions/intellij/intellij_generator_plugin/src/main/resources/templates/with_equatable/bloc.dart.template
  extensions/intellij/intellij_generator_plugin/src/main/resources/templates/with_equatable/bloc_event.dart.template
  extensions/intellij/intellij_generator_plugin/src/main/resources/templates/with_equatable/bloc_exports.dart.template
  extensions/intellij/intellij_generator_plugin/src/main/resources/templates/with_equatable/bloc_state.dart.template
  extensions/intellij/intellij_generator_plugin/src/main/resources/templates/without_equatable/bloc.dart.template
  extensions/intellij/intellij_generator_plugin/src/main/resources/templates/without_equatable/bloc_event.dart.template
  extensions/intellij/intellij_generator_plugin/src/main/resources/templates/without_equatable/bloc_exports.dart.template
  extensions/intellij/intellij_generator_plugin/src/main/resources/templates/without_equatable/bloc_state.dart.template
Labels: enhancement

#162 bloc v0.11.0
  packages/bloc/CHANGELOG.md
  packages/bloc/README.md
  packages/bloc/example/main.dart
  packages/bloc/lib/src/bloc.dart
  packages/bloc/pubspec.yaml
  packages/bloc/test/bloc_delegate_test.dart
  packages/bloc/test/helpers/async/async_bloc.dart
  packages/bloc/test/helpers/complex/complex_bloc.dart
  packages/bloc/test/helpers/counter/counter_bloc.dart
  packages/bloc/test/helpers/counter/counter_exception_bloc.dart
  packages/bloc/test/helpers/counter/on_error_bloc.dart
  packages/bloc/test/helpers/simple/simple_bloc.dart
Labels: enhancement
