Repository felangel/bloc, pull requests merged in 2019-10, with the labels that each got.

#566 Fix typo in flutterfirestoretodostutorial.md
  docs/flutterfirestoretodostutorial.md
Labels: documentation, enhancement

#565 Update file structure in flutter firestore todos example
  docs/flutterfirestoretodostutorial.md
Labels: documentation, enhancement

#572 Refactor Bloc to extend Stream<State>
  packages/bloc/example/main.dart
  packages/bloc/lib/src/bloc.dart
  packages/bloc/test/bloc_delegate_test.dart
  packages/bloc/test/bloc_test.dart
  packages/bloc/test/helpers/async/async_bloc.dart
  packages/bloc/test/helpers/counter/counter_bloc.dart
  packages/bloc/test/helpers/counter/counter_error_bloc.dart
  packages/bloc/test/helpers/counter/counter_exception_bloc.dart
Labels: enhancement

#576 update flutter_bloc to use bloc v0.16.0
  packages/flutter_bloc/CHANGELOG.md
  packages/flutter_bloc/README.md
  packages/flutter_bloc/example/lib/main.dart
  packages/flutter_bloc/example/pubspec.yaml
  packages/flutter_bloc/lib/src/bloc_builder.dart
  packages/flutter_bloc/lib/src/bloc_listener.dart
  packages/flutter_bloc/lib/src/bloc_provider.dart
  packages/flutter_bloc/pubspec.yaml
  packages/flutter_bloc/test/bloc_builder_test.dart
  packages/flutter_bloc/test/bloc_listener_test.dart
  packages/flutter_bloc/test/bloc_provider_test.dart
  packages/flutter_bloc/test/multi_bloc_listener_test.dart
  packages/flutter_bloc/test/multi_bloc_provider_test.dart
Labels: enhancement

#578 update angular_bloc to use bloc v0.16.0
  examples/angular_counter/lib/src/counter_page/counter_bloc.dart
  examples/angular_counter/lib/src/counter_page/counter_page_component.dart
  examples/angular_counter/pubspec.yaml
  examples/github_search/angular_github_search/lib/src/search_form/search_bar/search_bar_component.dart
  examples/github_search/angular_github_search/lib/src/search_form/search_form_component.dart
  packages/angular_bloc/CHANGELOG.md
  packages/angular_bloc/README.md
  packages/angular_bloc/example/example.dart
  packages/angular_bloc/lib/src/pipes/bloc_pipe.dart
  packages/angular_bloc/pubspec.yaml
  packages/angular_bloc/test/bloc_pipe_test.dart
Labels: enhancement

#579 create bloc_test package
  .travis.yml
  docs/assets/bloc_test_logo_full.png
  packages/bloc_test/CHANGELOG.md
  packages/bloc_test/LICENSE
  packages/bloc_test/README.md
  packages/bloc_test/analysis_options.yaml
  packages/bloc_test/example/main.dart
  packages/bloc_test/lib/bloc_test.dart
  packages/bloc_test/lib/src/when_listen.dart
  packages/bloc_test/pubspec.yaml
  packages/bloc_test/test/helpers/counter_bloc.dart
  packages/bloc_test/test/helpers/helpers.dart
  packages/bloc_test/test/helpers/sum_bloc.dart
  packages/bloc_test/test/when_listen_test.dart
Labels: enhancement

#589 [flutter_firebase_login] add WidgetsFlutterBinding.ensureInitialized()
  examples/flutter_firebase_login/lib/main.dart
Labels: enhancement, example

#583 Bloc v1.0.0
  packages/bloc/CHANGELOG.md
  packages/bloc/lib/src/bloc.dart
  packages/bloc/pubspec.yaml
  packages/bloc/test/deprecated_bloc_test.dart
Labels: enhancement

#591 flutter_bloc v1.0.0
  packages/flutter_bloc/CHANGELOG.md
  packages/flutter_bloc/pubspec.yaml
Labels: enhancement

#592 angular_bloc v1.0.0
  packages/angular_bloc/CHANGELOG.md
  packages/angular_bloc/pubspec.yaml
Labels: enhancement

#593 bloc_test v1.0.0
  packages/bloc_test/CHANGELOG.md
  packages/bloc_test/pubspec.yaml
Labels: enhancement

#598 Czech docs w/o Tutorials
  docs/_navbar.md
  docs/cs/README.md
  docs/cs/_coverpage.md
  docs/cs/_sidebar.md
  docs/cs/angularcountertutorial.md
  docs/cs/architecture.md
  docs/cs/blocintellijextension.md
  docs/cs/blocvscodeextension.md
  docs/cs/coreconcepts.md
  docs/cs/flutterangulargithubsearch.md
  docs/cs/flutterbloccoreconcepts.md
  docs/cs/fluttercountertutorial.md
  docs/cs/flutterfirebaselogintutorial.md
  docs/cs/flutterfirestoretodostutorial.md
  docs/cs/flutterinfinitelisttutorial.md
  docs/cs/flutterlogintutorial.md
  docs/cs/fluttertimertutorial.md
  docs/cs/fluttertodostutorial.md
  docs/cs/flutterweathertutorial.md
  docs/cs/gettingstarted.md
  docs/cs/recipesflutterblocaccess.md
  docs/cs/recipesflutternavigation.md
  docs/cs/recipesfluttershowsnackbar.md
  docs/cs/testing.md
  docs/cs/whybloc.md
  docs/index.html
Labels: documentation, translation

#617 apply effective-dart style to bloc package
  packages/bloc/README.md
  packages/bloc/analysis_options.yaml
  packages/bloc/lib/bloc.dart
  packages/bloc/lib/src/bloc.dart
  packages/bloc/lib/src/bloc_delegate.dart
  packages/bloc/lib/src/transition.dart
  packages/bloc/pubspec.yaml
  packages/bloc/test/bloc_delegate_test.dart
  packages/bloc/test/bloc_test.dart
  packages/bloc/test/helpers/complex/complex_bloc.dart
  packages/bloc/test/helpers/counter/counter.dart
  packages/bloc/test/helpers/helpers.dart
  packages/bloc/test/transition_test.dart
Labels: enhancement

#618 apply effective-dart style to flutter_bloc package
  .gitignore
  packages/flutter_bloc/README.md
  packages/flutter_bloc/analysis_options.yaml
  packages/flutter_bloc/lib/src/bloc_builder.dart
  packages/flutter_bloc/lib/src/bloc_listener.dart
  packages/flutter_bloc/lib/src/bloc_provider.dart
  packages/flutter_bloc/lib/src/multi_bloc_listener.dart
  packages/flutter_bloc/lib/src/multi_bloc_provider.dart
  packages/flutter_bloc/lib/src/multi_repository_provider.dart
  packages/flutter_bloc/lib/src/repository_provider.dart
  packages/flutter_bloc/pubspec.yaml
  packages/flutter_bloc/test/bloc_builder_test.dart
  packages/flutter_bloc/test/bloc_listener_test.dart
  packages/flutter_bloc/test/bloc_provider_test.dart
  packages/flutter_bloc/test/multi_bloc_listener_test.dart
  packages/flutter_bloc/test/multi_bloc_provider_test.dart
  packages/flutter_bloc/test/multi_repository_provider_test.dart
  packages/flutter_bloc/test/repository_provider_test.dart
Labels: enhancement

#620 update effective_dart to v1.1.0
  packages/bloc/analysis_options.yaml
  packages/bloc/lib/src/bloc.dart
  packages/bloc/lib/src/bloc_delegate.dart
  packages/bloc/lib/src/bloc_supervisor.dart
  packages/bloc/lib/src/transition.dart
  packages/bloc/pubspec.yaml
Labels: enhancement

#621 apply effective-dart style to angular_bloc package
  packages/angular_bloc/README.md
  packages/angular_bloc/analysis_options.yaml
  packages/angular_bloc/lib/src/pipes/bloc_pipe.dart
  packages/angular_bloc/pubspec.yaml
Labels: enhancement

#622 apply effective-dart style to bloc_test package
  packages/bloc_test/README.md
  packages/bloc_test/analysis_options.yaml
  packages/bloc_test/pubspec.yaml
Labels: enhancement
