Repository felangel/bloc, pull requests merged in 2019-05, with the labels that each got.

#262 dispose while events are pending does not emit new states or trigger onError
  packages/bloc/README.md
  packages/bloc/lib/src/bloc.dart
  packages/bloc/test/bloc_test.dart
Labels: enhancement

#263 expose bloc event stream
  packages/bloc/lib/src/bloc.dart
  packages/bloc/test/bloc_test.dart
Labels: enhancement

#266 update rxdart to ^0.22.0
  packages/bloc/pubspec.yaml
Labels: enhancement

#267 Include bloc in BlocDelegate onTransition and onError
  packages/bloc/README.md
  packages/bloc/example/main.dart
  packages/bloc/lib/src/bloc.dart
  packages/bloc/lib/src/bloc_delegate.dart
  packages/bloc/test/bloc_delegate_test.dart
  packages/bloc/test/bloc_test.dart
Labels: enhancement

#268 Add onEvent to Bloc and BlocDelegate
  packages/bloc/README.md
  packages/bloc/example/main.dart
  packages/bloc/lib/src/bloc.dart
  packages/bloc/lib/src/bloc_delegate.dart
  packages/bloc/test/bloc_delegate_test.dart
  packages/bloc/test/bloc_test.dart
  packages/bloc/test/helpers/counter/counter_bloc.dart
Labels: enhancement

#285 Update README.md
  README.md
Labels: documentation

#302 Add Autofocus on BlocName Input to IntelliJ Plugin
  extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/action/GenerateBlocDialog.java
Labels: enhancement, extension

#305 Improve BlocDelegate Initialization
  packages/bloc/CHANGELOG.md
  packages/bloc/example/main.dart
  packages/bloc/lib/src/bloc.dart
  packages/bloc/lib/src/bloc_supervisor.dart
  packages/bloc/pubspec.yaml
  packages/bloc/test/bloc_delegate_test.dart
  packages/bloc/test/bloc_supervisor_test.dart
  packages/bloc/test/bloc_test.dart
Labels: enhancement

#306 Fix IntelliJ Bloc Generator Name Casing
  extensions/intellij/intellij_generator_plugin/build.gradle
  extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/generator/Generator.kt
  extensions/intellij/intellij_generator_plugin/src/main/resources/templates/with_equatable/bloc.dart.template
  extensions/intellij/intellij_generator_plugin/src/main/resources/templates/with_equatable/bloc_event.dart.template
  extensions/intellij/intellij_generator_plugin/src/main/resources/templates/with_equatable/bloc_state.dart.template
  extensions/intellij/intellij_generator_plugin/src/main/resources/templates/without_equatable/bloc.dart.template
  extensions/intellij/intellij_generator_plugin/src/main/resources/templates/without_equatable/bloc_event.dart.template
  extensions/intellij/intellij_generator_plugin/src/main/resources/templates/without_equatable/bloc_state.dart.template
Labels: bug, extension

#319 Add optional condition to BlocBuilder
  packages/flutter_bloc/CHANGELOG.md
  packages/flutter_bloc/README.md
  packages/flutter_bloc/lib/src/bloc_builder.dart
  packages/flutter_bloc/pubspec.yaml
  packages/flutter_bloc/test/bloc_builder_test.dart
Labels: enhancement
