Repository felangel/bloc, pull requests merged in 2019-06, with the labels that each got.

#329 Fix null previousState in BlocBuilder condition
  packages/flutter_bloc/CHANGELOG.md
  packages/flutter_bloc/lib/src/bloc_builder.dart
  packages/flutter_bloc/pubspec.yaml
  packages/flutter_bloc/test/bloc_builder_test.dart
Labels: bug

#333 deprecate bloc event stream
  packages/bloc/CHANGELOG.md
  packages/bloc/lib/src/bloc.dart
  packages/bloc/pubspec.yaml
Labels: deprecation

#344 Update BlocProvider to automatically dispose blocs
  packages/flutter_bloc/example/lib/main.dart
  packages/flutter_bloc/lib/src/bloc_provider.dart
  packages/flutter_bloc/test/bloc_provider_test.dart
  packages/flutter_bloc/test/bloc_provider_tree_test.dart
Labels: enhancement

#347 Expose dispose method on BlocProvider
  packages/flutter_bloc/README.md
  packages/flutter_bloc/example/lib/main.dart
  packages/flutter_bloc/lib/src/bloc_provider.dart
  packages/flutter_bloc/test/bloc_provider_test.dart
Labels: enhancement

#349 Update BlocProvider to Automatically Dispose Bloc
  packages/flutter_bloc/CHANGELOG.md
  packages/flutter_bloc/README.md
  packages/flutter_bloc/example/lib/main.dart
  packages/flutter_bloc/lib/src/bloc_provider.dart
  packages/flutter_bloc/pubspec.yaml
  packages/flutter_bloc/test/bloc_provider_test.dart
Labels: enhancement

#370 BlocListener should only be called on state changes
  packages/flutter_bloc/CHANGELOG.md
  packages/flutter_bloc/lib/src/bloc_listener.dart
  packages/flutter_bloc/pubspec.yaml
  packages/flutter_bloc/test/bloc_listener_test.dart
  packages/flutter_bloc/test/bloc_listener_tree_test.dart
Labels: bug

#377 fix BlocProvider copyWith()
  packages/flutter_bloc/lib/src/bloc_provider.dart
Labels: bug
