Repository felangel/bloc, pull requests merged in 2019-12, with the labels that each got.

#610 Czech docs: typos, improvements & tutorials
  docs/cs/README.md
  docs/cs/coreconcepts.md
  docs/cs/flutterbloccoreconcepts.md
  docs/cs/gettingstarted.md
  docs/cs/recipesfluttershowsnackbar.md
  docs/cs/testing.md
Labels: documentation, translation

#722 fix word in the docs pt-br whybloc.md
  docs/pt-br/whybloc.md
Labels: documentation, enhancement

#723 add bloc naming conventions to docs
  docs/_sidebar.md
  docs/blocnamingconventions.md
Labels: documentation, enhancement

#742 add wait to blocTest and duration to emitsExactly
  packages/bloc_test/CHANGELOG.md
  packages/bloc_test/README.md
  packages/bloc_test/lib/src/bloc_test.dart
  packages/bloc_test/lib/src/emits_exactly.dart
  packages/bloc_test/test/bloc_test_test.dart
  packages/bloc_test/test/emits_exactly_test.dart
  packages/bloc_test/test/helpers/debounce_counter_bloc.dart
  packages/bloc_test/test/helpers/helpers.dart
Labels: enhancement, pkg:bloc_test

#749 Expose lazy parameter on RepositoryProvider and BlocProvider
  packages/flutter_bloc/lib/src/bloc_builder.dart
  packages/flutter_bloc/lib/src/bloc_listener.dart
  packages/flutter_bloc/lib/src/bloc_provider.dart
  packages/flutter_bloc/lib/src/repository_provider.dart
  packages/flutter_bloc/pubspec.yaml
  packages/flutter_bloc/test/bloc_provider_test.dart
  packages/flutter_bloc/test/multi_bloc_provider_test.dart
  packages/flutter_bloc/test/repository_provider_test.dart
Labels: enhancement

#753 Add BlocConsumer
  docs/flutterbloccoreconcepts.md
  packages/flutter_bloc/README.md
  packages/flutter_bloc/lib/src/bloc_consumer.dart
  packages/flutter_bloc/test/bloc_consumer_test.dart
Labels: enhancement, pkg:flutter_bloc
