Repository felangel/bloc, pull requests merged in 2019-02, with the labels that each got.

#90 bloc v0.8.3
  packages/bloc/CHANGELOG.md
  packages/bloc/pubspec.yaml
Labels: release candidate

#91 flutter_bloc v0.5.4
  packages/flutter_bloc/CHANGELOG.md
  packages/flutter_bloc/pubspec.yaml
Labels: release candidate

#97 Handle Exceptions in MapEventToState
  packages/bloc/lib/src/bloc.dart
  packages/bloc/test/bloc_test.dart
  packages/bloc/test/helpers/counter/counter.dart
  packages/bloc/test/helpers/counter/counter_exception_bloc.dart
Labels: enhancement

#99 bloc v0.9.0 rc
  docs/_coverpage.md
  docs/coreconcepts.md
  packages/bloc/CHANGELOG.md
  packages/bloc/pubspec.yaml
  packages/bloc/test/bloc_delegate_test.dart
Labels: release candidate

#100 flutter_bloc v0.6.0 rc
  docs/flutterangulargithubsearch.md
  docs/fluttercountertutorial.md
  docs/flutterlogintutorial.md
  docs/gettingstarted.md
  examples/flutter_infinite_list/lib/bloc/simple_bloc_delegate.dart
  examples/flutter_login/lib/main.dart
  examples/flutter_weather/lib/main.dart
  packages/angular_bloc/pubspec.yaml
  packages/flutter_bloc/CHANGELOG.md
  packages/flutter_bloc/example/lib/main.dart
  packages/flutter_bloc/pubspec.yaml
Labels: release candidate

#101 angular_bloc v0.4.0 rc
  docs/angularcountertutorial.md
  docs/flutterangulargithubsearch.md
  docs/fluttercountertutorial.md
  docs/flutterinfinitelisttutorial.md
  docs/flutterlogintutorial.md
  docs/flutterweathertutorial.md
  docs/gettingstarted.md
  examples/angular_counter/web/main.dart
  examples/github_search/angular_github_search/pubspec.yaml
  examples/github_search/common_github_search/pubspec.yaml
  examples/github_search/flutter_github_search/pubspec.yaml
  packages/angular_bloc/CHANGELOG.md
  packages/angular_bloc/pubspec.yaml
Labels: release candidate

#102 From the most recent to the oldest version.
  packages/bloc/CHANGELOG.md
Labels: documentation

#105 restrict rxdart to < 0.21.0
  packages/angular_bloc/pubspec.yaml
  packages/bloc/CHANGELOG.md
  packages/bloc/pubspec.yaml
  packages/flutter_bloc/pubspec.yaml
  performance_tests/flutter_bloc/bloc_builder/pubspec.yaml
  performance_tests/flutter_bloc/bloc_provider/pubspec.yaml
Labels: bug

#107 Update flutter_bloc and angular_bloc to require bloc v0.9.3
  packages/angular_bloc/CHANGELOG.md
  packages/angular_bloc/pubspec.yaml
  packages/flutter_bloc/CHANGELOG.md
  packages/flutter_bloc/pubspec.yaml
Labels: bug
