Repository felangel/bloc, pull requests merged in 2020-09, with the labels that each got.

#1684 fix(flutter_bloc): state synchronization issue
  packages/flutter_bloc/lib/src/bloc_builder.dart
  packages/flutter_bloc/lib/src/bloc_consumer.dart
  packages/flutter_bloc/test/bloc_builder_test.dart
  packages/flutter_bloc/test/bloc_consumer_test.dart
  packages/flutter_bloc/test/bloc_listener_test.dart
Labels: bug, pkg:flutter_bloc

#1688 chore(flutter_bloc): v6.0.4
  packages/flutter_bloc/CHANGELOG.md
  packages/flutter_bloc/pubspec.yaml
Labels: chore, pkg:flutter_bloc, release candidate

#1692 docs(bloc): add cubit and bloc flow diagrams
  docs/assets/bloc_flow.png
  docs/assets/cubit_flow.png
  packages/bloc/README.md
Labels: documentation

#1698 docs(bloc): internal organization and documentation improvements
  packages/bloc/lib/src/bloc.dart
Labels: documentation, pkg:bloc

#1699 fix(flutter_bloc): BlocBuilder builder and buildWhen state synchronization fix
  packages/flutter_bloc/lib/src/bloc_builder.dart
  packages/flutter_bloc/lib/src/bloc_listener.dart
  packages/flutter_bloc/test/bloc_builder_test.dart
Labels: bug, pkg:flutter_bloc

#1713 fix(bloc_test): add deep equality warning
  packages/bloc_test/CHANGELOG.md
  packages/bloc_test/lib/src/bloc_test.dart
  packages/bloc_test/pubspec.yaml
  packages/bloc_test/test/bloc_bloc_test_test.dart
Labels: pkg:bloc_test, release candidate

#1727 docs: support dark mode
  docs/index.html
Labels: documentation

#1735 docs: 3 Spanish Tutorials Updated and 1 added
  docs/angularcountertutorial.md
  docs/es/_coverpage.md
  docs/es/angularcountertutorial.md
  docs/es/fluttercountertutorial.md
  docs/es/flutterfirebaselogintutorial.md
  docs/es/flutterlogintutorial.md
Labels: documentation, translation

#1739 docs: minor typo fix in flutterfirebaselogintutorial.md
  docs/flutterfirebaselogintutorial.md
Labels: documentation

#1743 docs: Update coreconcepts.md
  docs/coreconcepts.md
Labels: documentation

#1755 docs: minor updates to why bloc
  docs/whybloc.md
Labels: documentation

#1772 refactor: upgrade dependencies for flutter firebase login example
  examples/flutter_firebase_login/.gitignore
  examples/flutter_firebase_login/ios/Flutter/.last_build_id
  examples/flutter_firebase_login/ios/Podfile
  examples/flutter_firebase_login/ios/Runner.xcodeproj/project.pbxproj
  examples/flutter_firebase_login/lib/main.dart
  examples/flutter_firebase_login/packages/authentication_repository/lib/src/authentication_repository.dart
  examples/flutter_firebase_login/packages/authentication_repository/pubspec.yaml
  examples/flutter_firebase_login/packages/authentication_repository/test/authentication_repository_test.dart
Labels: example

#1777 docs: add missing SignUpForm section to FirebaseLogin
  docs/flutterfirebaselogintutorial.md
Labels: documentation, example
