Repository felangel/bloc, pull requests merged in 2020-01, with the labels that each got.

#760 bloc_test v3.0.1
  packages/bloc_test/CHANGELOG.md
  packages/bloc_test/lib/src/bloc_test.dart
  packages/bloc_test/pubspec.yaml
  packages/bloc_test/test/bloc_test_test.dart
Labels: bug, pkg:bloc_test

#768 Upgrade to effective_dart 1.2.0
  packages/angular_bloc/analysis_options.yaml
  packages/angular_bloc/lib/src/pipes/bloc_pipe.dart
  packages/angular_bloc/pubspec.yaml
  packages/bloc/analysis_options.yaml
  packages/bloc/example/main.dart
  packages/bloc/lib/src/bloc.dart
  packages/bloc/lib/src/bloc_delegate.dart
  packages/bloc/lib/src/bloc_supervisor.dart
  packages/bloc/lib/src/transition.dart
  packages/bloc/pubspec.yaml
  packages/bloc/test/bloc_delegate_test.dart
  packages/bloc/test/bloc_supervisor_test.dart
  packages/bloc/test/bloc_test.dart
  packages/bloc/test/helpers/async/async_event.dart
  packages/bloc/test/helpers/async/async_state.dart
  packages/bloc/test/helpers/complex/complex_bloc.dart
  packages/bloc/test/helpers/complex/complex_event.dart
  packages/bloc/test/helpers/complex/complex_state.dart
  packages/bloc/test/helpers/counter/counter_bloc.dart
  packages/bloc/test/transition_test.dart
  packages/bloc_test/analysis_options.yaml
  packages/bloc_test/example/main.dart
  packages/bloc_test/lib/src/bloc_test.dart
  packages/bloc_test/lib/src/emits_exactly.dart
  packages/bloc_test/lib/src/mock_bloc.dart
  packages/bloc_test/lib/src/when_listen.dart
  packages/bloc_test/pubspec.yaml
  packages/bloc_test/test/bloc_test_test.dart
  packages/bloc_test/test/emits_exactly_test.dart
  packages/flutter_bloc/analysis_options.yaml
  packages/flutter_bloc/lib/src/bloc_builder.dart
  packages/flutter_bloc/lib/src/bloc_consumer.dart
  packages/flutter_bloc/lib/src/bloc_listener.dart
  packages/flutter_bloc/lib/src/bloc_provider.dart
  packages/flutter_bloc/lib/src/multi_bloc_listener.dart
  packages/flutter_bloc/lib/src/multi_bloc_provider.dart
  packages/flutter_bloc/lib/src/multi_repository_provider.dart
  packages/flutter_bloc/lib/src/repository_provider.dart
  packages/flutter_bloc/pubspec.yaml
  packages/flutter_bloc/test/bloc_builder_test.dart
  packages/flutter_bloc/test/bloc_consumer_test.dart
  packages/flutter_bloc/test/bloc_listener_test.dart
  packages/flutter_bloc/test/bloc_provider_test.dart
  packages/flutter_bloc/test/multi_bloc_listener_test.dart
  packages/flutter_bloc/test/multi_bloc_provider_test.dart
  packages/flutter_bloc/test/multi_repository_provider_test.dart
  packages/flutter_bloc/test/repository_provider_test.dart
  performance_tests/flutter_bloc/bloc_builder/test_driver/main.dart
  performance_tests/flutter_bloc/bloc_provider/test_driver/main.dart
Labels: enhancement

#773 Fix MultiBlocProvider and MultiRepositoryProvider type inference
  packages/flutter_bloc/lib/flutter_bloc.dart
  packages/flutter_bloc/lib/src/bloc_listener.dart
  packages/flutter_bloc/lib/src/bloc_provider.dart
  packages/flutter_bloc/lib/src/multi_bloc_listener.dart
  packages/flutter_bloc/lib/src/multi_bloc_provider.dart
  packages/flutter_bloc/lib/src/multi_repository_provider.dart
  packages/flutter_bloc/lib/src/repository_provider.dart
  packages/flutter_bloc/test/bloc_provider_test.dart
  packages/flutter_bloc/test/multi_bloc_listener_test.dart
  packages/flutter_bloc/test/multi_bloc_provider_test.dart
  packages/flutter_bloc/test/multi_repository_provider_test.dart
  packages/flutter_bloc/test/repository_provider_test.dart
Labels: enhancement, pkg:flutter_bloc

#775 Add Naming Conventions to Contributing list
  CONTRIBUTING.md
Labels: documentation

#785 Spanish documentation
  docs/_navbar.md
  docs/es/README.md
  docs/es/_coverpage.md
  docs/es/_sidebar.md
  docs/es/gettingstarted.md
  docs/index.html
Labels: documentation, translation

#552 French docs
  docs/fr/_sidebar.md
  docs/fr/architecture.md
  docs/fr/coreconcepts.md
  docs/fr/fluttercountertutorial.md
  docs/fr/flutterinfinitelisttutorial.md
  docs/fr/flutterlogintutorial.md
  docs/fr/fluttertimertutorial.md
  docs/fr/gettingstarted.md
  docs/fr/testing.md
  docs/fr/whybloc.md
Labels: documentation, translation

#794 Spanish docs
  docs/es/README.md
  docs/es/_coverpage.md
  docs/es/coreconcepts.md
  docs/es/flutterbloccoreconcepts.md
  docs/es/whybloc.md
Labels: documentation, translation

#800 Minor template code style improvements
  extensions/intellij/intellij_generator_plugin/src/main/resources/templates/with_equatable/bloc.dart.template
  extensions/intellij/intellij_generator_plugin/src/main/resources/templates/with_equatable/bloc_exports.dart.template
  extensions/intellij/intellij_generator_plugin/src/main/resources/templates/without_equatable/bloc.dart.template
  extensions/intellij/intellij_generator_plugin/src/main/resources/templates/without_equatable/bloc_exports.dart.template
  extensions/vscode/src/templates/bloc.template.ts
Labels: enhancement, extension

#777 Add GitHub CI
  .github/workflows/main.yaml
  .travis.yml
  README.md
  packages/angular_bloc/README.md
  packages/bloc/README.md
  packages/bloc_test/README.md
  packages/flutter_bloc/README.md
Labels: ci

#803 Add FAQs to Docs
  docs/_sidebar.md
  docs/faqs.md
Labels: documentation

#804 Add verify to blocTest
  packages/bloc_test/CHANGELOG.md
  packages/bloc_test/README.md
  packages/bloc_test/lib/src/bloc_test.dart
  packages/bloc_test/pubspec.yaml
  packages/bloc_test/test/bloc_test_test.dart
  packages/bloc_test/test/helpers/helpers.dart
  packages/bloc_test/test/helpers/side_effect_counter_bloc.dart
Labels: enhancement, pkg:bloc_test

#816 Add extensions to BlocProvider & RepositoryProvider + Fix Provider Error Handling
  docs/flutterbloccoreconcepts.md
  packages/flutter_bloc/CHANGELOG.md
  packages/flutter_bloc/README.md
  packages/flutter_bloc/example/lib/main.dart
  packages/flutter_bloc/lib/src/bloc_provider.dart
  packages/flutter_bloc/lib/src/repository_provider.dart
  packages/flutter_bloc/test/bloc_provider_test.dart
  packages/flutter_bloc/test/repository_provider_test.dart
Labels: enhancement, pkg:flutter_bloc, release candidate

#818 update ci to use v1.12.13+hotfix.7
  .github/workflows/main.yaml
Labels: ci

#824 Update docs flutter_bloc dependencies to 3.2.0
  docs/cs/flutterangulargithubsearch.md
  docs/cs/fluttercountertutorial.md
  docs/cs/flutterfirebaselogintutorial.md
  docs/cs/flutterfirestoretodostutorial.md
  docs/cs/flutterinfinitelisttutorial.md
  docs/cs/flutterlogintutorial.md
  docs/cs/fluttertimertutorial.md
  docs/cs/fluttertodostutorial.md
  docs/cs/flutterweathertutorial.md
  docs/cs/gettingstarted.md
  docs/es/gettingstarted.md
  docs/flutterangulargithubsearch.md
  docs/fluttercountertutorial.md
  docs/flutterfirebaselogintutorial.md
  docs/flutterfirestoretodostutorial.md
  docs/flutterinfinitelisttutorial.md
  docs/flutterlogintutorial.md
  docs/fluttertimertutorial.md
  docs/fluttertodostutorial.md
  docs/flutterweathertutorial.md
  docs/gettingstarted.md
  docs/pt-br/gettingstarted.md
  docs/ru/flutterangulargithubsearch.md
  docs/ru/fluttercountertutorial.md
  docs/ru/flutterfirebaselogintutorial.md
  docs/ru/flutterfirestoretodostutorial.md
  docs/ru/flutterinfinitelisttutorial.md
  docs/ru/flutterlogintutorial.md
  docs/ru/fluttertimertutorial.md
  docs/ru/fluttertodostutorial.md
  docs/ru/flutterweathertutorial.md
  docs/ru/gettingstarted.md
Labels: documentation, enhancement, example

#827 Main Ci improvements
  .github/workflows/main.yaml
Labels: ci

#829 Docs spelling fixes
  docs/cs/fluttertodostutorial.md
  docs/faqs.md
  docs/flutterbloccoreconcepts.md
  docs/fluttertodostutorial.md
  docs/fr/flutterinfinitelisttutorial.md
Labels: documentation, enhancement
