Repository felangel/bloc, pull requests merged in 2020-06, with the labels that each got.

#1235 Translation to zh-cn: recipesfluttershowsnackbar.md
  docs/zh-cn/recipesfluttershowsnackbar.md
Labels: documentation, translation

#1239 Translation to zh-cn: recipesflutternavigation.md
  docs/zh-cn/recipesflutterblocaccess.md
  docs/zh-cn/recipesflutternavigation.md
Labels: documentation, translation

#1219 Update architecture.md
  docs/architecture.md
Labels: documentation, enhancement

#1243 docs: update architecture.md translations
  docs/az/architecture.md
  docs/cs/architecture.md
  docs/es/architecture.md
  docs/fr/architecture.md
  docs/jp/architecture.md
  docs/ko-kr/architecture.md
  docs/pt-br/architecture.md
  docs/ru/architecture.md
  docs/zh-cn/architecture.md
Labels: documentation, translation

#1245 Fully translated Readme.md to french
  docs/fr/README.md
Labels: documentation, translation

#1247 Correct the condition for the form_validation
  examples/flutter_form_validation/lib/main.dart
Labels: bug, example

#1252 docs: reuse snippets for flutterangulargithubsearch
  docs/_snippets/flutter_angular_github_search/angular/app_component.dart.md
  docs/_snippets/flutter_angular_github_search/angular/pubspec.yaml.md
  docs/_snippets/flutter_angular_github_search/angular/search_bar_component.dart.md
  docs/_snippets/flutter_angular_github_search/angular/search_bar_component.html.md
  docs/_snippets/flutter_angular_github_search/angular/search_body_component.dart.md
  docs/_snippets/flutter_angular_github_search/angular/search_body_component.html.md
  docs/_snippets/flutter_angular_github_search/angular/search_form_component.dart.md
  docs/_snippets/flutter_angular_github_search/angular/search_form_component.html.md
  docs/_snippets/flutter_angular_github_search/angular/search_result_item_component.dart.md
  docs/_snippets/flutter_angular_github_search/angular/search_result_item_component.html.md
  docs/_snippets/flutter_angular_github_search/angular/search_results_component.dart.md
  docs/_snippets/flutter_angular_github_search/angular/search_results_component.html.md
  docs/_snippets/flutter_angular_github_search/angular/stagehand.sh.md
  docs/_snippets/flutter_angular_github_search/common/github_cache.dart.md
  docs/_snippets/flutter_angular_github_search/common/github_client.dart.md
  docs/_snippets/flutter_angular_github_search/common/github_repository.dart.md
  docs/_snippets/flutter_angular_github_search/common/github_search_bloc.dart.md
  docs/_snippets/flutter_angular_github_search/common/github_search_event.dart.md
  docs/_snippets/flutter_angular_github_search/common/github_search_state.dart.md
  docs/_snippets/flutter_angular_github_search/common/github_user.dart.md
  docs/_snippets/flutter_angular_github_search/common/pub_get.sh.md
  docs/_snippets/flutter_angular_github_search/common/pubspec.yaml.md
  docs/_snippets/flutter_angular_github_search/common/search_result.dart.md
  docs/_snippets/flutter_angular_github_search/common/search_result_error.dart.md
  docs/_snippets/flutter_angular_github_search/common/search_result_item.dart.md
  docs/_snippets/flutter_angular_github_search/common/setup1.sh.md
  docs/_snippets/flutter_angular_github_search/common/setup2.sh.md
  docs/_snippets/flutter_angular_github_search/flutter/flutter_create.sh.md
  docs/_snippets/flutter_angular_github_search/flutter/flutter_packages_get.sh.md
  docs/_snippets/flutter_angular_github_search/flutter/main.dart.md
  docs/_snippets/flutter_angular_github_search/flutter/pubspec.yaml.md
  docs/_snippets/flutter_angular_github_search/flutter/search_bar.dart.md
  docs/_snippets/flutter_angular_github_search/flutter/search_body.dart.md
  docs/_snippets/flutter_angular_github_search/flutter/search_form.dart.md
  docs/_snippets/flutter_angular_github_search/flutter/search_form_complete.dart.md
  docs/_snippets/flutter_angular_github_search/flutter/search_result_item.dart.md
  docs/_snippets/flutter_angular_github_search/flutter/search_results.dart.md
  docs/cs/flutterangulargithubsearch.md
  docs/flutterangulargithubsearch.md
  docs/jp/flutterangulargithubsearch.md
  docs/pt-br/flutterangulargithubsearch.md
  docs/ru/flutterangulargithubsearch.md
  docs/zh-cn/flutterangulargithubsearch.md
Labels: documentation, example

#1255 docs: reuse snippets for flutterfirebaselogin
  docs/_snippets/flutter_firebase_login_tutorial/authentication_bloc.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/authentication_bloc_constructor.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/authentication_bloc_dir.sh.md
  docs/_snippets/flutter_firebase_login_tutorial/authentication_bloc_initial_state.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/authentication_bloc_map_event_to_state.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/authentication_event.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/authentication_state.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/create_account_button.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/flutter_create.sh.md
  docs/_snippets/flutter_firebase_login_tutorial/flutter_packages_get.sh.md
  docs/_snippets/flutter_firebase_login_tutorial/google_login_button.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/home_screen.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/is_signed_in_and_get_user.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/login_barrel.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/login_bloc.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/login_bloc_dir.sh.md
  docs/_snippets/flutter_firebase_login_tutorial/login_button.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/login_event.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/login_form.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/login_screen.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/login_state.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/main1.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/main2.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/main3.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/main4.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/main5.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/main6.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/pubspec.yaml.md
  docs/_snippets/flutter_firebase_login_tutorial/register_barrel.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/register_bloc.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/register_bloc_dir.sh.md
  docs/_snippets/flutter_firebase_login_tutorial/register_button.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/register_event.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/register_form.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/register_screen.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/register_state.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/sign_in_with_credentials.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/sign_in_with_google.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/sign_out.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/sign_up.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/simple_bloc_delegate.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/splash_screen.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/user_repository.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/user_repository_constructor.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/validators.dart.md
  docs/cs/flutterfirebaselogintutorial.md
  docs/flutterfirebaselogintutorial.md
  docs/fr/flutterfirebaselogintutorial.md
  docs/jp/flutterfirebaselogintutorial.md
  docs/pt-br/flutterfirebaselogintutorial.md
  docs/ru/flutterfirebaselogintutorial.md
  docs/zh-cn/flutterfirebaselogintutorial.md
Labels: documentation

#1257 docs: reuse snippets for flutterfirestoretodos
  docs/_snippets/flutter_firestore_todos_tutorial/authentication_bloc.dart.md
  docs/_snippets/flutter_firestore_todos_tutorial/authentication_event.dart.md
  docs/_snippets/flutter_firestore_todos_tutorial/authentication_state.dart.md
  docs/_snippets/flutter_firestore_todos_tutorial/entities_barrel.dart.md
  docs/_snippets/flutter_firestore_todos_tutorial/firebase_todos_repository.dart.md
  docs/_snippets/flutter_firestore_todos_tutorial/firebase_user_repository.dart.md
  docs/_snippets/flutter_firestore_todos_tutorial/main.dart.md
  docs/_snippets/flutter_firestore_todos_tutorial/map_load_todos_to_state.dart.md
  docs/_snippets/flutter_firestore_todos_tutorial/map_todos_updated_to_state.dart.md
  docs/_snippets/flutter_firestore_todos_tutorial/pubspec.yaml.md
  docs/_snippets/flutter_firestore_todos_tutorial/todo.dart.md
  docs/_snippets/flutter_firestore_todos_tutorial/todo_entity.dart.md
  docs/_snippets/flutter_firestore_todos_tutorial/todos_bloc.dart.md
  docs/_snippets/flutter_firestore_todos_tutorial/todos_repository.dart.md
  docs/_snippets/flutter_firestore_todos_tutorial/todos_repository_dir.sh.md
  docs/_snippets/flutter_firestore_todos_tutorial/todos_repository_library.dart.md
  docs/_snippets/flutter_firestore_todos_tutorial/todos_repository_pubspec.yaml.md
  docs/_snippets/flutter_firestore_todos_tutorial/user_repository.dart.md
  docs/_snippets/flutter_firestore_todos_tutorial/user_repository_dir.sh.md
  docs/_snippets/flutter_firestore_todos_tutorial/user_repository_library.dart.md
  docs/_snippets/flutter_firestore_todos_tutorial/user_repository_pubspec.yaml.md
  docs/cs/flutterfirestoretodostutorial.md
  docs/flutterfirestoretodostutorial.md
  docs/jp/flutterfirestoretodostutorial.md
  docs/pt-br/flutterfirestoretodostutorial.md
  docs/ru/flutterfirestoretodostutorial.md
  docs/zh-cn/flutterfirestoretodostutorial.md
Labels: documentation

#1259 docs: reuse snippets for flutterlogintutorial
  docs/_snippets/flutter_login_tutorial/authentication_bloc.dart.md
  docs/_snippets/flutter_login_tutorial/authentication_bloc_constructor.dart.md
  docs/_snippets/flutter_login_tutorial/authentication_bloc_initial_state.dart.md
  docs/_snippets/flutter_login_tutorial/authentication_bloc_map_event_to_state.dart.md
  docs/_snippets/flutter_login_tutorial/authentication_event.dart.md
  docs/_snippets/flutter_login_tutorial/authentication_state.dart.md
  docs/_snippets/flutter_login_tutorial/flutter_create.sh.md
  docs/_snippets/flutter_login_tutorial/flutter_packages_get.sh.md
  docs/_snippets/flutter_login_tutorial/home_page.dart.md
  docs/_snippets/flutter_login_tutorial/loading_indicator.dart.md
  docs/_snippets/flutter_login_tutorial/login_bloc.dart.md
  docs/_snippets/flutter_login_tutorial/login_event.dart.md
  docs/_snippets/flutter_login_tutorial/login_form.dart.md
  docs/_snippets/flutter_login_tutorial/login_page.dart.md
  docs/_snippets/flutter_login_tutorial/login_state.dart.md
  docs/_snippets/flutter_login_tutorial/main.dart.md
  docs/_snippets/flutter_login_tutorial/pubspec.yaml.md
  docs/_snippets/flutter_login_tutorial/splash_page.dart.md
  docs/_snippets/flutter_login_tutorial/user_repository.dart.md
  docs/cs/flutterlogintutorial.md
  docs/es/flutterlogintutorial.md
  docs/flutterlogintutorial.md
  docs/fr/flutterlogintutorial.md
  docs/jp/flutterlogintutorial.md
  docs/pt-br/flutterlogintutorial.md
  docs/ru/flutterlogintutorial.md
  docs/zh-cn/flutterlogintutorial.md
Labels: documentation

#1261 docs: reuse snippets for fluttertimertutorial
  docs/_snippets/flutter_timer_tutorial/actions.dart.md
  docs/_snippets/flutter_timer_tutorial/background.dart.md
  docs/_snippets/flutter_timer_tutorial/flutter_create.sh.md
  docs/_snippets/flutter_timer_tutorial/main1.dart.md
  docs/_snippets/flutter_timer_tutorial/main2.dart.md
  docs/_snippets/flutter_timer_tutorial/pubspec.yaml.md
  docs/_snippets/flutter_timer_tutorial/ticker.dart.md
  docs/_snippets/flutter_timer_tutorial/timer1.dart.md
  docs/_snippets/flutter_timer_tutorial/timer2.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_bloc.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_bloc_barrel.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_bloc_empty.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_bloc_initial_state.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_bloc_pause.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_bloc_resume.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_bloc_start.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_bloc_tick.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_bloc_ticker.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_event.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_state.dart.md
  docs/cs/fluttertimertutorial.md
  docs/es/fluttertimertutorial.md
  docs/fluttertimertutorial.md
  docs/fr/fluttertimertutorial.md
  docs/jp/fluttertimertutorial.md
  docs/pt-br/fluttertimertutorial.md
  docs/ru/fluttertimertutorial.md
  docs/zh-cn/fluttertimertutorial.md
Labels: documentation

#1263 docs: reuse snippets for fluttertodostutorial
  docs/_snippets/flutter_todos_tutorial/add_edit_screen.dart.md
  docs/_snippets/flutter_todos_tutorial/app_tab.dart.md
  docs/_snippets/flutter_todos_tutorial/blocs_barrel.dart.md
  docs/_snippets/flutter_todos_tutorial/delete_todo_snack_bar.dart.md
  docs/_snippets/flutter_todos_tutorial/details_screen.dart.md
  docs/_snippets/flutter_todos_tutorial/extra_action.dart.md
  docs/_snippets/flutter_todos_tutorial/extra_actions.dart.md
  docs/_snippets/flutter_todos_tutorial/filter_button.dart.md
  docs/_snippets/flutter_todos_tutorial/filtered_todos.dart.md
  docs/_snippets/flutter_todos_tutorial/filtered_todos_bloc.dart.md
  docs/_snippets/flutter_todos_tutorial/filtered_todos_bloc_barrel.dart.md
  docs/_snippets/flutter_todos_tutorial/filtered_todos_event.dart.md
  docs/_snippets/flutter_todos_tutorial/filtered_todos_state.dart.md
  docs/_snippets/flutter_todos_tutorial/flutter_create.sh.md
  docs/_snippets/flutter_todos_tutorial/flutter_packages_get.sh.md
  docs/_snippets/flutter_todos_tutorial/flutter_todos_keys.dart.md
  docs/_snippets/flutter_todos_tutorial/home_screen.dart.md
  docs/_snippets/flutter_todos_tutorial/loading_indicator.dart.md
  docs/_snippets/flutter_todos_tutorial/localization.dart.md
  docs/_snippets/flutter_todos_tutorial/main1.dart.md
  docs/_snippets/flutter_todos_tutorial/main2.dart.md
  docs/_snippets/flutter_todos_tutorial/multi_bloc_provider.dart.md
  docs/_snippets/flutter_todos_tutorial/nested_bloc_providers.dart.md
  docs/_snippets/flutter_todos_tutorial/pubspec.yaml.md
  docs/_snippets/flutter_todos_tutorial/screens_barrel.dart.md
  docs/_snippets/flutter_todos_tutorial/simple_bloc_delegate.dart.md
  docs/_snippets/flutter_todos_tutorial/stats.dart.md
  docs/_snippets/flutter_todos_tutorial/stats_bloc.dart.md
  docs/_snippets/flutter_todos_tutorial/stats_event.dart.md
  docs/_snippets/flutter_todos_tutorial/stats_state.dart.md
  docs/_snippets/flutter_todos_tutorial/tab_bloc.dart.md
  docs/_snippets/flutter_todos_tutorial/tab_bloc_barrel.dart.md
  docs/_snippets/flutter_todos_tutorial/tab_event.dart.md
  docs/_snippets/flutter_todos_tutorial/tab_selector.dart.md
  docs/_snippets/flutter_todos_tutorial/todo.dart.md
  docs/_snippets/flutter_todos_tutorial/todo_item.dart.md
  docs/_snippets/flutter_todos_tutorial/todos_app.dart.md
  docs/_snippets/flutter_todos_tutorial/todos_bloc.dart.md
  docs/_snippets/flutter_todos_tutorial/todos_bloc_barrel.dart.md
  docs/_snippets/flutter_todos_tutorial/todos_event.dart.md
  docs/_snippets/flutter_todos_tutorial/todos_state.dart.md
  docs/_snippets/flutter_todos_tutorial/visibility_filter.dart.md
  docs/cs/fluttertodostutorial.md
  docs/fluttertodostutorial.md
  docs/fr/fluttertodostutorial.md
  docs/jp/fluttertodostutorial.md
  docs/pt-br/fluttertodostutorial.md
  docs/ru/fluttertodostutorial.md
  docs/zh-cn/fluttertodostutorial.md
Labels: documentation

#1276 docs: update flutterfirebaselogintutorial to adhere to naming conventions
  docs/_snippets/flutter_firebase_login_tutorial/authentication_bloc.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/authentication_bloc_initial_state.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/authentication_bloc_map_event_to_state.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/authentication_event.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/authentication_state.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/home_screen.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/login_bloc.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/login_event.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/login_form.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/login_state.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/main1.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/main2.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/main3.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/main4.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/main5.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/main6.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/register_bloc.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/register_event.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/register_form.dart.md
  docs/_snippets/flutter_firebase_login_tutorial/register_state.dart.md
  docs/cs/flutterfirebaselogintutorial.md
  docs/flutterfirebaselogintutorial.md
  docs/fr/flutterfirebaselogintutorial.md
  docs/jp/flutterfirebaselogintutorial.md
  docs/pt-br/flutterfirebaselogintutorial.md
  docs/ru/flutterfirebaselogintutorial.md
  docs/zh-cn/flutterfirebaselogintutorial.md
Labels: documentation, example

#1278 docs: update flutterinfinitelisttutorial to adhere to naming conventions
  docs/_snippets/flutter_infinite_list_tutorial/home_page.dart.md
  docs/_snippets/flutter_infinite_list_tutorial/main.dart.md
  docs/_snippets/flutter_infinite_list_tutorial/post_bloc.dart.md
  docs/_snippets/flutter_infinite_list_tutorial/post_bloc_initial_state.dart.md
  docs/_snippets/flutter_infinite_list_tutorial/post_bloc_map_event_to_state.dart.md
  docs/_snippets/flutter_infinite_list_tutorial/post_event.dart.md
  docs/_snippets/flutter_infinite_list_tutorial/post_state.dart.md
  docs/cs/flutterinfinitelisttutorial.md
  docs/es/flutterinfinitelisttutorial.md
  docs/flutterinfinitelisttutorial.md
  docs/fr/flutterinfinitelisttutorial.md
  docs/jp/flutterinfinitelisttutorial.md
  docs/pt-br/flutterinfinitelisttutorial.md
  docs/ru/flutterinfinitelisttutorial.md
  docs/zh-cn/flutterinfinitelisttutorial.md
Labels: documentation, example

#1280 docs: update flutterlogintutorial to adhere to naming conventions
  docs/_snippets/flutter_login_tutorial/authentication_bloc.dart.md
  docs/_snippets/flutter_login_tutorial/authentication_bloc_initial_state.dart.md
  docs/_snippets/flutter_login_tutorial/authentication_bloc_map_event_to_state.dart.md
  docs/_snippets/flutter_login_tutorial/authentication_event.dart.md
  docs/_snippets/flutter_login_tutorial/authentication_state.dart.md
  docs/_snippets/flutter_login_tutorial/home_page.dart.md
  docs/_snippets/flutter_login_tutorial/login_bloc.dart.md
  docs/_snippets/flutter_login_tutorial/login_form.dart.md
  docs/_snippets/flutter_login_tutorial/login_state.dart.md
  docs/_snippets/flutter_login_tutorial/main.dart.md
  docs/cs/flutterlogintutorial.md
  docs/es/flutterlogintutorial.md
  docs/flutterlogintutorial.md
  docs/fr/flutterlogintutorial.md
  docs/jp/flutterlogintutorial.md
  docs/pt-br/flutterlogintutorial.md
  docs/ru/flutterlogintutorial.md
  docs/zh-cn/flutterlogintutorial.md
Labels: documentation, example

#1291 docs: update fluttertimertutorial to adhere to naming conventions
  docs/_snippets/flutter_timer_tutorial/actions.dart.md
  docs/_snippets/flutter_timer_tutorial/main2.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_bloc.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_bloc_initial_state.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_bloc_pause.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_bloc_resume.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_bloc_start.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_bloc_tick.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_bloc_ticker.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_event.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_state.dart.md
  docs/cs/fluttertimertutorial.md
  docs/es/fluttertimertutorial.md
  docs/fluttertimertutorial.md
  docs/fr/fluttertimertutorial.md
  docs/jp/fluttertimertutorial.md
  docs/pt-br/fluttertimertutorial.md
  docs/ru/fluttertimertutorial.md
  docs/zh-cn/fluttertimertutorial.md
  examples/flutter_timer/lib/bloc/timer_event.dart
  examples/flutter_timer/lib/bloc/timer_state.dart
Labels: documentation

#1296 docs: update docs/flutterinfinitelist to match code
  docs/cs/flutterinfinitelisttutorial.md
  docs/es/flutterinfinitelisttutorial.md
  docs/flutterinfinitelisttutorial.md
  docs/fr/flutterinfinitelisttutorial.md
  docs/jp/flutterinfinitelisttutorial.md
  docs/pt-br/flutterinfinitelisttutorial.md
  docs/ru/flutterinfinitelisttutorial.md
  docs/zh-cn/flutterinfinitelisttutorial.md
Labels: bug, documentation

#1298 rc(flutter_bloc): v4.0.1
  packages/flutter_bloc/CHANGELOG.md
  packages/flutter_bloc/pubspec.yaml
Labels: pkg:flutter_bloc, release candidate

#1322 update rxdart to 0.24.0
  packages/bloc/pubspec.yaml
Labels: enhancement, pkg:bloc

#1360 feat(bloc): addError
  .gitignore
  README.md
  packages/bloc/CHANGELOG.md
  packages/bloc/README.md
  packages/bloc/example/main.dart
  packages/bloc/lib/src/bloc.dart
  packages/bloc/lib/src/bloc_observer.dart
  packages/bloc/pubspec.yaml
  packages/bloc/test/bloc_observer_test.dart
  packages/bloc/test/bloc_test.dart
Labels: enhancement, pkg:bloc, release candidate

#1362 Fixed doc error in the bloc access recipe
  docs/_snippets/recipes_flutter_bloc_access/anonymous_route_access/main.dart.md
Labels: bug, documentation
