Repository felangel/bloc, pull requests merged in 2020-05, with the labels that each got.

#1133 bloc_test: whenListen stubs state as well
  packages/bloc_test/CHANGELOG.md
  packages/bloc_test/README.md
  packages/bloc_test/lib/src/when_listen.dart
  packages/bloc_test/test/when_listen_test.dart
Labels: enhancement, pkg:bloc_test, release candidate

#1129 bloc_test v5.1.0
  packages/bloc_test/CHANGELOG.md
  packages/bloc_test/README.md
  packages/bloc_test/lib/src/bloc_test.dart
  packages/bloc_test/lib/src/when_listen.dart
  packages/bloc_test/pubspec.yaml
  packages/bloc_test/test/bloc_test_test.dart
  packages/bloc_test/test/helpers/exception_counter_bloc.dart
  packages/bloc_test/test/helpers/helpers.dart
  packages/bloc_test/test/when_listen_test.dart
Labels: enhancement, pkg:bloc_test, release candidate

#1132 flutterfirebaselogintutorial.md Fully translated to french
  docs/fr/flutterfirebaselogintutorial.md
Labels: documentation, translation

#1139 Translated the addition, revised a word
  docs/zh-cn/README.md
Labels: documentation, translation

#1141 Translation of fluttertodostutorial.md to french
  docs/fr/flutterfirebaselogintutorial.md
  docs/fr/fluttertodostutorial.md
Labels: documentation, translation

#1157 ci: upgrade to flutter v1.17.0
  .github/workflows/main.yaml
  docs/cs/fluttertodostutorial.md
  docs/fluttertodostutorial.md
  docs/fr/fluttertodostutorial.md
  docs/jp/fluttertodostutorial.md
  docs/pt-br/fluttertodostutorial.md
  docs/ru/fluttertodostutorial.md
  docs/zh-cn/fluttertodostutorial.md
  examples/flutter_firestore_todos/lib/screens/add_edit_screen.dart
  examples/flutter_firestore_todos/lib/screens/details_screen.dart
  examples/flutter_firestore_todos/lib/widgets/filter_button.dart
  examples/flutter_firestore_todos/lib/widgets/stats.dart
  examples/flutter_firestore_todos/lib/widgets/todo_item.dart
  examples/flutter_shopping_cart/lib/cart/my_cart.dart
  examples/flutter_shopping_cart/lib/catalog/my_catalog.dart
  examples/flutter_todos/lib/screens/add_edit_screen.dart
  examples/flutter_todos/lib/screens/details_screen.dart
  examples/flutter_todos/lib/widgets/filter_button.dart
  examples/flutter_todos/lib/widgets/stats.dart
  examples/flutter_todos/lib/widgets/todo_item.dart
Labels: ci

#1173 included the latest update
  docs/zh-cn/faqs.md
Labels: documentation, translation

#1176 ESP translation => Add note about copying Equatable props to FAQs (#1067)
  .github/workflows/main.yaml
  docs/es/README.md
  docs/es/faqs.md
  docs/pt-br/README.md
Labels: documentation, translation

#1177 ci: upgrade to flutter v1.17.1
  .github/workflows/main.yaml
Labels: ci

#1140 Update Examples to Adhere to Naming Conventions
  examples/flutter_bloc_with_stream/lib/bloc/ticker_bloc.dart
  examples/flutter_bloc_with_stream/lib/bloc/ticker_event.dart
  examples/flutter_bloc_with_stream/lib/bloc/ticker_state.dart
  examples/flutter_bloc_with_stream/lib/main.dart
  examples/flutter_dynamic_form/lib/bloc/new_car_bloc.dart
  examples/flutter_dynamic_form/lib/bloc/new_car_event.dart
  examples/flutter_dynamic_form/lib/bloc/new_car_state.dart
  examples/flutter_dynamic_form/lib/main.dart
  examples/flutter_firebase_login/lib/authentication_bloc/authentication_bloc.dart
  examples/flutter_firebase_login/lib/authentication_bloc/authentication_event.dart
  examples/flutter_firebase_login/lib/authentication_bloc/authentication_state.dart
  examples/flutter_firebase_login/lib/home_screen.dart
  examples/flutter_firebase_login/lib/login/bloc/login_bloc.dart
  examples/flutter_firebase_login/lib/login/bloc/login_event.dart
  examples/flutter_firebase_login/lib/login/bloc/login_state.dart
  examples/flutter_firebase_login/lib/login/login_form.dart
  examples/flutter_firebase_login/lib/main.dart
  examples/flutter_firebase_login/lib/register/bloc/register_bloc.dart
  examples/flutter_firebase_login/lib/register/bloc/register_event.dart
  examples/flutter_firebase_login/lib/register/bloc/register_state.dart
  examples/flutter_firebase_login/lib/register/register_form.dart
  examples/flutter_infinite_list/lib/bloc/post_bloc.dart
  examples/flutter_infinite_list/lib/bloc/post_event.dart
  examples/flutter_infinite_list/lib/bloc/post_state.dart
  examples/flutter_infinite_list/lib/main.dart
  examples/flutter_login/lib/authentication/authentication_bloc.dart
  examples/flutter_login/lib/authentication/authentication_event.dart
  examples/flutter_login/lib/authentication/authentication_state.dart
  examples/flutter_login/lib/home/home_page.dart
  examples/flutter_login/lib/login/bloc/login_bloc.dart
  examples/flutter_login/lib/login/bloc/login_state.dart
  examples/flutter_login/lib/login/login_form.dart
  examples/flutter_login/lib/login/login_page.dart
  examples/flutter_login/lib/main.dart
  examples/flutter_login/test/unit/authentication/authentication_bloc_test.dart
  examples/flutter_login/test/unit/authentication/authentication_event_test.dart
  examples/flutter_login/test/unit/login/login_bloc_test.dart
  examples/flutter_login/test/unit/login/login_event_test.dart
  examples/flutter_login/test/unit/login/login_state_test.dart
  examples/flutter_timer/lib/bloc/timer_bloc.dart
  examples/flutter_timer/lib/bloc/timer_event.dart
  examples/flutter_timer/lib/bloc/timer_state.dart
  examples/flutter_timer/lib/main.dart
Labels: enhancement, example

#1180 angular_bloc v5.0.0-dev.1
  examples/angular_counter/lib/src/counter_page/counter_page_component.css
  examples/angular_counter/lib/src/counter_page/counter_page_component.dart
  examples/angular_counter/lib/src/counter_page/counter_page_component.html
  examples/angular_counter/pubspec.yaml
  packages/angular_bloc/CHANGELOG.md
  packages/angular_bloc/README.md
  packages/angular_bloc/pubspec.yaml
Labels: pkg:angular_bloc, release candidate

#1183 Update translation to french
  docs/fr/blocintellijextension.md
  docs/fr/blocnamingconventions.md
  docs/fr/blocvscodeextension.md
  docs/fr/faqs.md
Labels: documentation, translation

#1185 ci: refactor pipeline to run intelligently
  .github/workflows/angular_bloc.yaml
  .github/workflows/angular_dart_examples.yaml
  .github/workflows/bloc.yaml
  .github/workflows/bloc_test.yaml
  .github/workflows/ci.yaml
  .github/workflows/dart_examples.yaml
  .github/workflows/docs.yaml
  .github/workflows/flutter_bloc.yaml
  .github/workflows/flutter_examples.yaml
  .github/workflows/main.yaml
Labels: ci

#1184 Correct links, translated counter app tutorial page
  docs/zh-cn/_sidebar.md
  docs/zh-cn/fluttercountertutorial.md
Labels: documentation, translation

#1187 ci: upload coverage to codecov
  .github/workflows/angular_bloc.yaml
  .github/workflows/bloc.yaml
  .github/workflows/bloc_test.yaml
  .github/workflows/flutter_bloc.yaml
Labels: ci

#1190 ci: fix optional test command
  .github/workflows/angular_dart_examples.yaml
  .github/workflows/ci.yaml
  .github/workflows/dart_examples.yaml
  .github/workflows/flutter_examples.yaml
Labels: ci

#1198 docs: improve flutter_form_validation example to use formz
  examples/flutter_form_validation/ios/Runner.xcodeproj/project.pbxproj
  examples/flutter_form_validation/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  examples/flutter_form_validation/lib/bloc/my_form_bloc.dart
  examples/flutter_form_validation/lib/bloc/my_form_event.dart
  examples/flutter_form_validation/lib/bloc/my_form_state.dart
  examples/flutter_form_validation/lib/main.dart
  examples/flutter_form_validation/lib/models/email.dart
  examples/flutter_form_validation/lib/models/models.dart
  examples/flutter_form_validation/lib/models/password.dart
  examples/flutter_form_validation/pubspec.yaml
Labels: enhancement, example

#1199 Spanish docs update
  docs/es/README.md
  docs/es/blocvscodeextension.md
Labels: documentation, translation

#1207 Removed duplicate text (Documentation Russian translation)
  docs/ru/flutterbloccoreconcepts.md
Labels: bug, documentation

#1208 Added missing letter (Russian translation mistake)
  docs/ru/flutterbloccoreconcepts.md
Labels: bug, documentation

#1209 Removed duplicated text in English for the Russian documentation
  docs/ru/fluttertimertutorial.md
Labels: bug, documentation

#1214 Updated Russian documentation
  docs/ru/flutterinfinitelisttutorial.md
Labels: bug, documentation

#1217 Removed duplicated text which is translated (Russian translation)
  docs/ru/flutterlogintutorial.md
Labels: bug, documentation

#1230 Repeated traduction in BlocProvider pharagrap.
  docs/es/flutterbloccoreconcepts.md
Labels: bug, documentation, translation
