Repository felangel/bloc, pull requests merged in 2020-02, with the labels that each got.

#830 Clean up links
  README.md
  docs/_coverpage.md
  docs/blocintellijextension.md
  docs/blocvscodeextension.md
  docs/coreconcepts.md
  docs/cs/README.md
  docs/cs/_coverpage.md
  docs/cs/blocintellijextension.md
  docs/cs/blocvscodeextension.md
  docs/cs/coreconcepts.md
  docs/cs/flutterweathertutorial.md
  docs/cs/gettingstarted.md
  docs/es/README.md
  docs/es/_coverpage.md
  docs/es/coreconcepts.md
  docs/es/gettingstarted.md
  docs/flutterweathertutorial.md
  docs/fr/README.md
  docs/fr/_coverpage.md
  docs/fr/coreconcepts.md
  docs/fr/gettingstarted.md
  docs/gettingstarted.md
  docs/ko-kr/README.md
  docs/ko-kr/_coverpage.md
  docs/pt-br/README.md
  docs/pt-br/_coverpage.md
  docs/pt-br/gettingstarted.md
  docs/ru/README.md
  docs/ru/_coverpage.md
  docs/ru/blocintellijextension.md
  docs/ru/blocvscodeextension.md
  docs/ru/coreconcepts.md
  docs/ru/flutterweathertutorial.md
  docs/ru/gettingstarted.md
  examples/angular_counter/README.md
  examples/flutter_bloc_with_stream/README.md
  examples/flutter_form_validation/README.md
  examples/flutter_infinite_list/README.md
  examples/flutter_login/README.md
  examples/flutter_todos/README.md
  examples/flutter_weather/README.md
  examples/github_search/README.md
  examples/github_search/angular_github_search/README.md
  examples/github_search/flutter_github_search/README.md
  extensions/intellij/README.md
  extensions/vscode/README.md
  packages/angular_bloc/README.md
  packages/bloc/README.md
  packages/bloc_test/README.md
  packages/flutter_bloc/README.md
  performance_tests/flutter_bloc/bloc_builder/README.md
  performance_tests/flutter_bloc/bloc_provider/README.md
Labels: documentation, enhancement

#832 Replace incorrect pause with resume in timer tutorial
  docs/cs/fluttertimertutorial.md
  docs/fluttertimertutorial.md
  docs/fr/fluttertimertutorial.md
  docs/ru/fluttertimertutorial.md
  examples/flutter_timer/lib/bloc/timer_bloc.dart
Labels: documentation, example

#833 Format docs
  docs/cs/architecture.md
  docs/cs/coreconcepts.md
  docs/es/README.md
  docs/es/_coverpage.md
  docs/es/coreconcepts.md
  docs/es/flutterbloccoreconcepts.md
  docs/es/whybloc.md
  docs/flutterfirebaselogintutorial.md
  docs/flutterweathertutorial.md
  docs/fr/architecture.md
  docs/fr/coreconcepts.md
  docs/fr/fluttercountertutorial.md
  docs/fr/flutterinfinitelisttutorial.md
  docs/fr/flutterlogintutorial.md
  docs/fr/fluttertimertutorial.md
  docs/fr/gettingstarted.md
  docs/fr/testing.md
  docs/fr/whybloc.md
  docs/pt-br/testing.md
  docs/ru/angularcountertutorial.md
  docs/ru/flutterangulargithubsearch.md
  docs/ru/fluttercountertutorial.md
  docs/ru/flutterfirebaselogintutorial.md
  docs/ru/flutterfirestoretodostutorial.md
  docs/ru/flutterinfinitelisttutorial.md
  docs/ru/flutterlogintutorial.md
  docs/ru/fluttertimertutorial.md
  docs/ru/fluttertodostutorial.md
  docs/ru/flutterweathertutorial.md
Labels: documentation

#834 Format pubspec.yaml
  examples/angular_counter/pubspec.yaml
Labels: example

#837 Add Multiple Subscription Tests to Bloc
  packages/bloc/test/bloc_test.dart
  packages/bloc/test/helpers/simple/simple_bloc.dart
Labels: enhancement, pkg:bloc

#821 Remove RxDart dependency from bloc package
  packages/bloc/lib/src/bloc.dart
  packages/bloc/pubspec.yaml
Labels: enhancement, pkg:bloc

#826 Fix pub paths
  packages/angular_bloc/pubspec.yaml
  packages/bloc/pubspec.yaml
  packages/bloc_test/pubspec.yaml
  packages/flutter_bloc/pubspec.yaml
Labels: bug, dependency, documentation

#813 pt-BR docs translations
  docs/pt-br/_sidebar.md
  docs/pt-br/angularcountertutorial.md
  docs/pt-br/architecture.md
  docs/pt-br/blocintellijextension.md
  docs/pt-br/blocnamingconventions.md
  docs/pt-br/blocvscodeextension.md
  docs/pt-br/coreconcepts.md
  docs/pt-br/faqs.md
  docs/pt-br/flutterangulargithubsearch.md
  docs/pt-br/flutterbloccoreconcepts.md
  docs/pt-br/fluttercountertutorial.md
  docs/pt-br/flutterfirebaselogintutorial.md
  docs/pt-br/flutterfirestoretodostutorial.md
  docs/pt-br/flutterinfinitelisttutorial.md
  docs/pt-br/flutterlogintutorial.md
  docs/pt-br/fluttertimertutorial.md
  docs/pt-br/fluttertodostutorial.md
  docs/pt-br/flutterweathertutorial.md
  docs/pt-br/recipesflutterblocaccess.md
  docs/pt-br/recipesflutternavigation.md
  docs/pt-br/recipesfluttershowsnackbar.md
Labels: documentation, translation

#855 Add missing tests to examples/flutter_login and examples/flutter_weather
  .github/workflows/main.yaml
  examples/flutter_login/lib/login/bloc/login_bloc.dart
  examples/flutter_login/lib/login/bloc/login_event.dart
  examples/flutter_login/lib/login/bloc/login_state.dart
  examples/flutter_login/lib/login/login.dart
  examples/flutter_login/lib/login/login_form.dart
  examples/flutter_login/lib/login/login_page.dart
  examples/flutter_login/lib/main.dart
  examples/flutter_login/pubspec.yaml
  examples/flutter_login/test/authentication/authentication_bloc_test.dart
  examples/flutter_login/test/login/login_bloc_test.dart
  examples/flutter_login/test/unit/authentication/authentication_bloc_test.dart
  examples/flutter_login/test/unit/authentication/authentication_event_test.dart
  examples/flutter_login/test/unit/login/login_bloc_test.dart
  examples/flutter_login/test/unit/login/login_event_test.dart
  examples/flutter_login/test/unit/login/login_state_test.dart
  examples/flutter_weather/pubspec.yaml
  examples/flutter_weather/test/blocs/weather_bloc_test.dart
  examples/flutter_weather/test/blocs/weather_event_test.dart
  examples/flutter_weather/test/models/weather_test.dart
  examples/flutter_weather/test/repositories/weather_api_client_test.dart
  examples/flutter_weather/test/repositories/weather_repository_test.dart
Labels: ci, example

#840 Bloc Internal Mapping to Transition
  packages/bloc/lib/src/bloc.dart
  packages/bloc/pubspec.yaml
  packages/bloc/test/bloc_test.dart
  packages/bloc/test/helpers/complex/complex_bloc.dart
  packages/bloc/test/helpers/counter/counter.dart
  packages/bloc/test/helpers/counter/flat_map_bloc.dart
Labels: enhancement candidate, feedback wanted, pkg:bloc

#869 Update flutterinfinitelisttutorial.md
  docs/flutterinfinitelisttutorial.md
  docs/fr/flutterinfinitelisttutorial.md
  docs/pt-br/flutterinfinitelisttutorial.md
  docs/ru/flutterinfinitelisttutorial.md
Labels: documentation

#883 Provide spanish translation to testing.md
  docs/es/testing.md
Labels: documentation, translation

#884 Provide spanish translation to architecture.md
  docs/es/architecture.md
Labels: documentation, translation

#887 Update examples/flutter_weather to cover completing the Completer
  docs/flutterweathertutorial.md
  docs/zh-cn/flutterweathertutorial.md
  examples/flutter_weather/lib/widgets/weather.dart
Labels: documentation, example

#890 Update RU translations to include #887
  docs/ru/flutterweathertutorial.md
Labels: documentation, translation

#893 Add Docs workflow
  .github/DOCS_ISSUE_TEMPLATE.md
  .github/workflows/docs.yaml
Labels: ci, translation

#886 Update Czech translations
  docs/cs/_sidebar.md
  docs/cs/blocnamingconventions.md
  docs/cs/faqs.md
Labels: documentation, translation

#895 Enhance docs workflow
  .github/DOCS_ISSUE_TEMPLATE.md
  CONTRIBUTING.md
Labels: ci, documentation

#896 Translate naming conventions
  docs/cs/blocnamingconventions.md
  docs/cs/flutterweathertutorial.md
Labels: documentation, translation

#907 Remove type from unused parameters
  packages/bloc/test/bloc_delegate_test.dart
  packages/bloc/test/bloc_test.dart
Labels: enhancement, pkg:bloc

#904 Make templates comments consistent with snippets
  extensions/intellij/intellij_generator_plugin/src/main/resources/templates/with_equatable/bloc.dart.template
  extensions/intellij/intellij_generator_plugin/src/main/resources/templates/without_equatable/bloc.dart.template
  extensions/vscode/src/templates/bloc.template.ts
Labels: enhancement, extension

#881 Chinese(simplified) docs
  docs/zh-cn/README.md
  docs/zh-cn/_coverpage.md
  docs/zh-cn/_navbar.md
  docs/zh-cn/_sidebar.md
  docs/zh-cn/architecture.md
  docs/zh-cn/blocnamingconventions.md
  docs/zh-cn/coreconcepts.md
  docs/zh-cn/faqs.md
  docs/zh-cn/flutterbloccoreconcepts.md
  docs/zh-cn/gettingstarted.md
  docs/zh-cn/testing.md
  docs/zh-cn/whybloc.md
Labels: documentation, translation

#913 bloc_test v4.0.0
  examples/flutter_login/test/unit/authentication/authentication_bloc_test.dart
  examples/flutter_login/test/unit/login/login_bloc_test.dart
  examples/flutter_weather/test/blocs/weather_bloc_test.dart
  packages/bloc_test/CHANGELOG.md
  packages/bloc_test/README.md
  packages/bloc_test/example/main.dart
  packages/bloc_test/lib/src/bloc_test.dart
  packages/bloc_test/lib/src/emits_exactly.dart
  packages/bloc_test/test/bloc_test_test.dart
  packages/bloc_test/test/emits_exactly_test.dart
Labels: enhancement, pkg:bloc_test, release candidate

#917 Upgrade CI to use Flutter Stable 1.12.13+hotfix.8
  .github/workflows/main.yaml
Labels: ci

#918 Update VSCode Bloc to v3.3.0
  extensions/vscode/CHANGELOG.md
  extensions/vscode/package.json
  extensions/vscode/src/utils/analyze-dependencies.ts
Labels: enhancement, extension

#859 Kr docs
  docs/ko-kr/README.md
  docs/ko-kr/_coverpage.md
  docs/ko-kr/_sidebar.md
  docs/ko-kr/architecture.md
  docs/ko-kr/blocnamingconventions.md
  docs/ko-kr/coreconcepts.md
  docs/ko-kr/gettingstarted.md
  docs/ko-kr/testing.md
  docs/ko-kr/whybloc.md
Labels: documentation, translation

#926 Updating pt-BR docs #925
  docs/pt-br/recipesflutterblocaccess.md
Labels: documentation, translation

#927 Add Named Route Access Recipe to docs/recipesflutterblocaccess: ru docs for 46d81c4
  docs/ru/recipesflutterblocaccess.md
Labels: documentation, translation

#929 renaming variables
  packages/flutter_bloc/lib/src/bloc_builder.dart
  packages/flutter_bloc/lib/src/bloc_listener.dart
Labels: internal enhancement
