Repository felangel/bloc, pull requests merged in 2021-06, with the labels that each got.

#2504 flutter_weather: refactor location models, tests to use JsonConverter
  examples/flutter_weather/packages/meta_weather_api/lib/src/models/location.dart
  examples/flutter_weather/packages/meta_weather_api/lib/src/models/location.g.dart
  examples/flutter_weather/packages/meta_weather_api/test/location_test.dart
Labels: bug, example

#2513 fix(bloc_test): revert mocktail export
  packages/bloc_test/CHANGELOG.md
  packages/bloc_test/lib/bloc_test.dart
  packages/bloc_test/pubspec.yaml
Labels: bug, pkg:bloc_test

#2512 docs(github_search): update tutorial
  docs/_snippets/flutter_angular_github_search/angular/app_component.dart.md
  docs/_snippets/flutter_angular_github_search/angular/pubspec.yaml.md
  docs/_snippets/flutter_angular_github_search/angular/search_body_component.dart.md
  docs/_snippets/flutter_angular_github_search/angular/search_body_component.html.md
  docs/_snippets/flutter_angular_github_search/angular/search_result_item_component.html.md
  docs/_snippets/flutter_angular_github_search/common/github_cache.dart.md
  docs/_snippets/flutter_angular_github_search/common/github_client.dart.md
  docs/_snippets/flutter_angular_github_search/common/github_repository.dart.md
  docs/_snippets/flutter_angular_github_search/common/github_search_bloc.dart.md
  docs/_snippets/flutter_angular_github_search/common/github_search_event.dart.md
  docs/_snippets/flutter_angular_github_search/common/github_search_state.dart.md
  docs/_snippets/flutter_angular_github_search/common/github_user.dart.md
  docs/_snippets/flutter_angular_github_search/common/pubspec.yaml.md
  docs/_snippets/flutter_angular_github_search/common/search_result.dart.md
  docs/_snippets/flutter_angular_github_search/common/search_result_error.dart.md
  docs/_snippets/flutter_angular_github_search/common/search_result_item.dart.md
  docs/_snippets/flutter_angular_github_search/flutter/main.dart.md
  docs/_snippets/flutter_angular_github_search/flutter/pubspec.yaml.md
  docs/_snippets/flutter_angular_github_search/flutter/search_bar.dart.md
  docs/_snippets/flutter_angular_github_search/flutter/search_body.dart.md
  docs/_snippets/flutter_angular_github_search/flutter/search_form.dart.md
  docs/_snippets/flutter_angular_github_search/flutter/search_form_complete.dart.md
  docs/_snippets/flutter_angular_github_search/flutter/search_result_item.dart.md
  docs/_snippets/flutter_angular_github_search/flutter/search_results.dart.md
  docs/cs/flutterangulargithubsearch.md
  docs/flutterangulargithubsearch.md
  docs/jp/flutterangulargithubsearch.md
  docs/pt-br/flutterangulargithubsearch.md
  docs/ru/flutterangulargithubsearch.md
  docs/zh-cn/flutterangulargithubsearch.md
Labels: documentation, example

#2514 docs(flutter_timer): update tutorial
  docs/_snippets/flutter_timer_tutorial/actions.dart.md
  docs/_snippets/flutter_timer_tutorial/background.dart.md
  docs/_snippets/flutter_timer_tutorial/main1.dart.md
  docs/_snippets/flutter_timer_tutorial/main2.dart.md
  docs/_snippets/flutter_timer_tutorial/pubspec.yaml.md
  docs/_snippets/flutter_timer_tutorial/ticker.dart.md
  docs/_snippets/flutter_timer_tutorial/timer1.dart.md
  docs/_snippets/flutter_timer_tutorial/timer2.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_bloc.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_bloc_barrel.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_bloc_empty.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_bloc_initial_state.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_bloc_pause.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_bloc_resume.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_bloc_start.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_bloc_tick.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_bloc_ticker.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_event.dart.md
  docs/_snippets/flutter_timer_tutorial/timer_state.dart.md
  docs/cs/fluttertimertutorial.md
  docs/es/fluttertimertutorial.md
  docs/fluttertimertutorial.md
  docs/fr/fluttertimertutorial.md
  docs/jp/fluttertimertutorial.md
  docs/pt-br/fluttertimertutorial.md
  docs/ru/fluttertimertutorial.md
  docs/zh-cn/fluttertimertutorial.md
Labels: documentation, example

#2508 docs(flutter_infinite_list): reached 100% test coverage
  examples/flutter_infinite_list/lib/main.dart
  examples/flutter_infinite_list/lib/posts/widgets/post_list_item.dart
  examples/flutter_infinite_list/pubspec.yaml
  examples/flutter_infinite_list/test/app_test.dart
  examples/flutter_infinite_list/test/posts/bloc/post_bloc_test.dart
  examples/flutter_infinite_list/test/posts/bloc/post_event_test.dart
  examples/flutter_infinite_list/test/posts/bloc/post_state_test.dart
  examples/flutter_infinite_list/test/posts/models/post_test.dart
  examples/flutter_infinite_list/test/posts/view/posts_list_test.dart
  examples/flutter_infinite_list/test/posts/view/posts_page_test.dart
Labels: example

#2442 refactor(flutter_firestore_todos): migrate to null safety
  examples/flutter_firestore_todos/ios/Podfile
  examples/flutter_firestore_todos/ios/Podfile.lock
  examples/flutter_firestore_todos/ios/Runner.xcodeproj/project.pbxproj
  examples/flutter_firestore_todos/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  examples/flutter_firestore_todos/lib/blocs/authentication_bloc/authentication_bloc.dart
  examples/flutter_firestore_todos/lib/blocs/authentication_bloc/authentication_state.dart
  examples/flutter_firestore_todos/lib/blocs/filtered_todos/filtered_todos_bloc.dart
  examples/flutter_firestore_todos/lib/blocs/simple_bloc_observer.dart
  examples/flutter_firestore_todos/lib/blocs/stats/stats_bloc.dart
  examples/flutter_firestore_todos/lib/blocs/todos/todos_bloc.dart
  examples/flutter_firestore_todos/lib/generated_plugin_registrant.dart
  examples/flutter_firestore_todos/lib/main.dart
  examples/flutter_firestore_todos/lib/screens/add_edit_screen.dart
  examples/flutter_firestore_todos/lib/screens/details_screen.dart
  examples/flutter_firestore_todos/lib/screens/home_screen.dart
  examples/flutter_firestore_todos/lib/widgets/delete_todo_snack_bar.dart
  examples/flutter_firestore_todos/lib/widgets/extra_actions.dart
  examples/flutter_firestore_todos/lib/widgets/filter_button.dart
  examples/flutter_firestore_todos/lib/widgets/filtered_todos.dart
  examples/flutter_firestore_todos/lib/widgets/tab_selector.dart
  examples/flutter_firestore_todos/lib/widgets/todo_item.dart
  examples/flutter_firestore_todos/pubspec.yaml
  examples/flutter_firestore_todos/todos_repository/lib/src/entities/todo_entity.dart
  examples/flutter_firestore_todos/todos_repository/lib/src/firebase_todos_repository.dart
  examples/flutter_firestore_todos/todos_repository/lib/src/models/todo.dart
  examples/flutter_firestore_todos/todos_repository/pubspec.yaml
  examples/flutter_firestore_todos/user_repository/lib/src/firebase_user_repository.dart
  examples/flutter_firestore_todos/user_repository/lib/src/user_repository.dart
  examples/flutter_firestore_todos/user_repository/pubspec.yaml
Labels: example

#2527 docs(bloc): update `onChange` description in README
  packages/bloc/README.md
Labels: documentation

#2536 docs: weather tutorial enhancements
  docs/cs/_sidebar.md
  docs/cs/flutterweathertutorial.md
  docs/es/flutterweathertutorial.md
  docs/flutterweathertutorial.md
  docs/fr/_sidebar.md
  docs/jp/_sidebar.md
  docs/jp/flutterweathertutorial.md
  docs/pt-br/flutterweathertutorial.md
  docs/ru/flutterweathertutorial.md
  docs/zh-cn/_sidebar.md
  docs/zh-cn/flutterweathertutorial.md
Labels: documentation

#2539 docs(flutter_weather): fix metaweather_api tests
  examples/flutter_weather/lib/main.dart
  examples/flutter_weather/packages/meta_weather_api/lib/src/meta_weather_api_client.dart
  examples/flutter_weather/packages/meta_weather_api/pubspec.yaml
  examples/flutter_weather/packages/meta_weather_api/test/meta_weather_api_client_test.dart
  examples/flutter_weather/packages/weather_repository/pubspec.yaml
  examples/flutter_weather/pubspec.yaml
Labels: bug, example

#2544 fix(vscode): wrap with selection
  extensions/vscode/src/utils/get-selected-text.ts
Labels: bug, extension

#2545 chore(vscode): v5.6.2
  extensions/vscode/CHANGELOG.md
  extensions/vscode/package-lock.json
  extensions/vscode/package.json
Labels: chore, extension, release candidate

#2550 docs(flutter_weather): fix pub.dev links to json serialization packages
  docs/flutterweathertutorial.md
Labels: documentation

#2560 docs: update stream sponsorship urls
  README.md
  docs/_coverpage.md
  docs/es/README.md
  packages/angular_bloc/README.md
  packages/bloc/README.md
  packages/bloc_test/README.md
  packages/flutter_bloc/README.md
  packages/hydrated_bloc/README.md
  packages/replay_bloc/README.md
Labels: documentation

#2557 docs: update timer tutorial
  docs/fluttertimertutorial.md
  examples/flutter_timer/pubspec.yaml
Labels: documentation

#2559 docs(flutter_infinite_list): tutorial updates
  docs/_snippets/flutter_infinite_list_tutorial/post_bloc_initial.dart.md
  docs/_snippets/flutter_infinite_list_tutorial/post_bloc_map_event_to_state.dart.md
  docs/flutterinfinitelisttutorial.md
Labels: documentation

#2564 docs: update sidebar tutorial links
  docs/_sidebar.md
  docs/az/_sidebar.md
  docs/ko-kr/_sidebar.md
Labels: documentation

#2522 docs(flutter_shopping_cart): reached 100% test coverage
  examples/flutter_shopping_cart/lib/app.dart
  examples/flutter_shopping_cart/lib/cart/bloc/cart_bloc.dart
  examples/flutter_shopping_cart/lib/cart/cart.dart
  examples/flutter_shopping_cart/lib/cart/models/cart.dart
  examples/flutter_shopping_cart/lib/cart/view/cart_page.dart
  examples/flutter_shopping_cart/lib/catalog/bloc/catalog_bloc.dart
  examples/flutter_shopping_cart/lib/catalog/bloc/catalog_event.dart
  examples/flutter_shopping_cart/lib/catalog/bloc/catalog_state.dart
  examples/flutter_shopping_cart/lib/catalog/catalog.dart
  examples/flutter_shopping_cart/lib/catalog/models/catalog.dart
  examples/flutter_shopping_cart/lib/catalog/models/item.dart
  examples/flutter_shopping_cart/lib/catalog/view/catalog_page.dart
  examples/flutter_shopping_cart/lib/main.dart
  examples/flutter_shopping_cart/lib/shopping_repository.dart
  examples/flutter_shopping_cart/lib/simple_bloc_observer.dart
  examples/flutter_shopping_cart/pubspec.yaml
  examples/flutter_shopping_cart/test/app_test.dart
  examples/flutter_shopping_cart/test/cart/bloc/cart_bloc_test.dart
  examples/flutter_shopping_cart/test/cart/bloc/cart_event_test.dart
  examples/flutter_shopping_cart/test/cart/bloc/cart_state_test.dart
  examples/flutter_shopping_cart/test/cart/models/cart_test.dart
  examples/flutter_shopping_cart/test/cart/view/cart_page_test.dart
  examples/flutter_shopping_cart/test/catalog/bloc/catalog_bloc_test.dart
  examples/flutter_shopping_cart/test/catalog/bloc/catalog_event_test.dart
  examples/flutter_shopping_cart/test/catalog/bloc/catalog_state_test.dart
  examples/flutter_shopping_cart/test/catalog/models/catalog_test.dart
  examples/flutter_shopping_cart/test/catalog/models/item_test.dart
  examples/flutter_shopping_cart/test/catalog/view/catalog_page_test.dart
  examples/flutter_shopping_cart/test/helper.dart
  examples/flutter_shopping_cart/test/shopping_repository_test.dart
Labels: example

#2567 docs: github_search tutorial updates
  docs/flutterangulargithubsearch.md
  examples/github_search/common_github_search/pubspec.yaml
Labels: documentation

#2570 docs(github_search): update sidebar
  docs/_sidebar.md
  docs/az/_sidebar.md
  docs/cs/_sidebar.md
  docs/es/_sidebar.md
  docs/fr/_sidebar.md
  docs/jp/_sidebar.md
  docs/ko-kr/_sidebar.md
  docs/pt-br/_sidebar.md
  docs/ru/_sidebar.md
  docs/zh-cn/_sidebar.md
Labels: documentation

#2581 fix(counter_example): integration_test dependency with null-safety
  examples/flutter_counter/pubspec.yaml
Labels: bug, example

#2574 docs: flutter login desktop support
  examples/flutter_login/linux/.gitignore
  examples/flutter_login/linux/CMakeLists.txt
  examples/flutter_login/linux/flutter/CMakeLists.txt
  examples/flutter_login/linux/flutter/generated_plugin_registrant.cc
  examples/flutter_login/linux/flutter/generated_plugin_registrant.h
  examples/flutter_login/linux/flutter/generated_plugins.cmake
  examples/flutter_login/linux/main.cc
  examples/flutter_login/linux/my_application.cc
  examples/flutter_login/linux/my_application.h
  examples/flutter_login/macos/.gitignore
  examples/flutter_login/macos/Flutter/Flutter-Debug.xcconfig
  examples/flutter_login/macos/Flutter/Flutter-Release.xcconfig
  examples/flutter_login/macos/Flutter/GeneratedPluginRegistrant.swift
  examples/flutter_login/macos/Runner.xcodeproj/project.pbxproj
  examples/flutter_login/macos/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  examples/flutter_login/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  examples/flutter_login/macos/Runner.xcworkspace/contents.xcworkspacedata
  examples/flutter_login/macos/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  examples/flutter_login/macos/Runner/AppDelegate.swift
  examples/flutter_login/macos/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  examples/flutter_login/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_1024.png
  examples/flutter_login/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_128.png
  examples/flutter_login/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_16.png
  examples/flutter_login/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_256.png
  examples/flutter_login/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_32.png
  examples/flutter_login/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_512.png
  examples/flutter_login/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_64.png
  examples/flutter_login/macos/Runner/Base.lproj/MainMenu.xib
  examples/flutter_login/macos/Runner/Configs/AppInfo.xcconfig
  examples/flutter_login/macos/Runner/Configs/Debug.xcconfig
  examples/flutter_login/macos/Runner/Configs/Release.xcconfig
  examples/flutter_login/macos/Runner/Configs/Warnings.xcconfig
  examples/flutter_login/macos/Runner/DebugProfile.entitlements
  examples/flutter_login/macos/Runner/Info.plist
  examples/flutter_login/macos/Runner/MainFlutterWindow.swift
  examples/flutter_login/macos/Runner/Release.entitlements
  examples/flutter_login/windows/.gitignore
  examples/flutter_login/windows/CMakeLists.txt
  examples/flutter_login/windows/flutter/CMakeLists.txt
  examples/flutter_login/windows/flutter/generated_plugin_registrant.cc
  examples/flutter_login/windows/flutter/generated_plugin_registrant.h
  examples/flutter_login/windows/flutter/generated_plugins.cmake
  examples/flutter_login/windows/runner/CMakeLists.txt
  examples/flutter_login/windows/runner/Runner.rc
  examples/flutter_login/windows/runner/flutter_window.cpp
  examples/flutter_login/windows/runner/flutter_window.h
  examples/flutter_login/windows/runner/main.cpp
  examples/flutter_login/windows/runner/resource.h
  examples/flutter_login/windows/runner/resources/app_icon.ico
  examples/flutter_login/windows/runner/run_loop.cpp
  examples/flutter_login/windows/runner/run_loop.h
  examples/flutter_login/windows/runner/runner.exe.manifest
  examples/flutter_login/windows/runner/utils.cpp
  examples/flutter_login/windows/runner/utils.h
  examples/flutter_login/windows/runner/win32_window.cpp
  examples/flutter_login/windows/runner/win32_window.h
Labels: example
