Repository felangel/bloc, pull requests merged in 2021-02, with the labels that each got.

#2120 fix: small error
  README.md
Labels: documentation

#2132 fix(flutter_bloc): BlocProvider.value use InheritedProvider.value
  packages/flutter_bloc/lib/src/bloc_provider.dart
  packages/flutter_bloc/test/bloc_provider_test.dart
Labels: bug, pkg:flutter_bloc

#2131 docs: add 'Key Topics' section to tutorials
  docs/angularcountertutorial.md
  docs/es/README.md
  docs/es/_coverpage.md
  docs/es/faqs.md
  docs/es/flutterbloccoreconcepts.md
  docs/es/flutterfirebaselogintutorial.md
  docs/es/flutterlogintutorial.md
  docs/es/fluttertimertutorial.md
  docs/es/migration.md
  docs/flutterangulargithubsearch.md
  docs/fluttercountertutorial.md
  docs/flutterfirebaselogintutorial.md
  docs/flutterfirestoretodostutorial.md
  docs/flutterinfinitelisttutorial.md
  docs/flutterlogintutorial.md
  docs/fluttertimertutorial.md
  docs/fluttertodostutorial.md
  docs/flutterweathertutorial.md
Labels: documentation, enhancement, translation

#2136 chore(flutter_bloc): v6.1.2
  packages/flutter_bloc/CHANGELOG.md
  packages/flutter_bloc/pubspec.yaml
Labels: chore, pkg:flutter_bloc

#2139 docs: update discord invite url
  CONTRIBUTING.md
  README.md
  docs/_coverpage.md
  docs/az/README.md
  docs/az/_coverpage.md
  docs/blocvscodeextension.md
  docs/cs/README.md
  docs/cs/_coverpage.md
  docs/cs/blocvscodeextension.md
  docs/es/README.md
  docs/es/_coverpage.md
  docs/es/blocvscodeextension.md
  docs/fr/README.md
  docs/fr/_coverpage.md
  docs/fr/blocvscodeextension.md
  docs/jp/README.md
  docs/jp/_coverpage.md
  docs/jp/blocvscodeextension.md
  docs/ko-kr/README.md
  docs/ko-kr/_coverpage.md
  docs/pt-br/README.md
  docs/pt-br/_coverpage.md
  docs/pt-br/blocvscodeextension.md
  docs/ru/README.md
  docs/ru/_coverpage.md
  docs/ru/blocvscodeextension.md
  docs/zh-cn/README.md
  docs/zh-cn/_coverpage.md
  docs/zh-cn/blocvscodeextension.md
  extensions/vscode/README.md
  packages/angular_bloc/README.md
  packages/bloc/README.md
  packages/bloc_test/README.md
  packages/flutter_bloc/README.md
  packages/hydrated_bloc/README.md
  packages/replay_bloc/README.md
Labels: documentation

#2143 feat(flutter_infinite_list): null safety
  examples/flutter_infinite_list/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  examples/flutter_infinite_list/lib/posts/bloc/post_bloc.dart
  examples/flutter_infinite_list/lib/posts/bloc/post_state.dart
  examples/flutter_infinite_list/lib/posts/models/post.dart
  examples/flutter_infinite_list/lib/posts/view/posts_list.dart
  examples/flutter_infinite_list/lib/posts/widgets/post_list_item.dart
  examples/flutter_infinite_list/pubspec.yaml
Labels: example, refactor

#2151 docs: Add zh-cn translations getting started overview
  docs/zh-cn/gettingstarted.md
Labels: translation

#2152 docs: add zh_cn translation to blocvscodeextension.md
  docs/zh-cn/blocvscodeextension.md
Labels: translation

#2146 Format the code snippet of BlocBuilder
  packages/flutter_bloc/lib/src/bloc_builder.dart
Labels: documentation, pkg:flutter_bloc

#2147 update the migration guide
  docs/es/migration.md
Labels: documentation

#2148 migrate flutter_form_validation to null safety
  examples/flutter_form_validation/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  examples/flutter_form_validation/lib/bloc/my_form_bloc.dart
  examples/flutter_form_validation/lib/bloc/my_form_event.dart
  examples/flutter_form_validation/lib/bloc/my_form_state.dart
  examples/flutter_form_validation/lib/main.dart
  examples/flutter_form_validation/lib/models/email.dart
  examples/flutter_form_validation/lib/models/password.dart
  examples/flutter_form_validation/pubspec.yaml
Labels: example, refactor

#2149 migrate github search to null safety
  examples/github_search/common_github_search/lib/src/github_cache.dart
  examples/github_search/common_github_search/lib/src/github_client.dart
  examples/github_search/common_github_search/lib/src/github_repository.dart
  examples/github_search/common_github_search/lib/src/github_search_bloc/github_search_bloc.dart
  examples/github_search/common_github_search/lib/src/github_search_bloc/github_search_event.dart
  examples/github_search/common_github_search/lib/src/github_search_bloc/github_search_state.dart
  examples/github_search/common_github_search/lib/src/models/github_user.dart
  examples/github_search/common_github_search/lib/src/models/search_result.dart
  examples/github_search/common_github_search/lib/src/models/search_result_error.dart
  examples/github_search/common_github_search/lib/src/models/search_result_item.dart
  examples/github_search/common_github_search/pubspec.yaml
  examples/github_search/flutter_github_search/ios/Flutter/Debug.xcconfig
  examples/github_search/flutter_github_search/ios/Flutter/Release.xcconfig
  examples/github_search/flutter_github_search/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  examples/github_search/flutter_github_search/lib/main.dart
  examples/github_search/flutter_github_search/lib/search_form.dart
  examples/github_search/flutter_github_search/pubspec.yaml
Labels: example, refactor

#2165 ci(bloc_test): update bloc_test.yaml workflow with new dart syntax
  .github/workflows/bloc_test.yaml
Labels: ci

#2176 docs: fixed definition of BlocListener
  docs/flutterfirebaselogintutorial.md
  docs/flutterfirestoretodostutorial.md
  docs/flutterlogintutorial.md
  docs/flutterweathertutorial.md
Labels: documentation
