Repository felangel/bloc, pull requests merged in 2022-06, with the labels that each got.

#3374 Replace Scaffold.of(context) with ScaffoldMessenger.of(context)
  docs/_snippets/recipes_flutter_show_snack_bar/main.dart.md
Labels: documentation

#3390 chore(flutter_bloc_with_stream): upgrade to Dart 2.17
  examples/flutter_bloc_with_stream/.metadata
  examples/flutter_bloc_with_stream/analysis_options.yaml
  examples/flutter_bloc_with_stream/android/app/build.gradle
  examples/flutter_bloc_with_stream/android/app/src/debug/AndroidManifest.xml
  examples/flutter_bloc_with_stream/android/app/src/main/res/values-night/styles.xml
  examples/flutter_bloc_with_stream/android/app/src/main/res/values/styles.xml
  examples/flutter_bloc_with_stream/android/app/src/profile/AndroidManifest.xml
  examples/flutter_bloc_with_stream/android/build.gradle
  examples/flutter_bloc_with_stream/android/gradle/wrapper/gradle-wrapper.properties
  examples/flutter_bloc_with_stream/ios/Runner.xcodeproj/project.pbxproj
  examples/flutter_bloc_with_stream/ios/Runner/Info.plist
  examples/flutter_bloc_with_stream/lib/main.dart
  examples/flutter_bloc_with_stream/pubspec.yaml
  examples/flutter_bloc_with_stream/test/ticker_page_test.dart
Labels: chore

#3391 chore(flutter_complex_list): upgrade to Dart 2.17
  examples/flutter_complex_list/.metadata
  examples/flutter_complex_list/analysis_options.yaml
  examples/flutter_complex_list/android/app/build.gradle
  examples/flutter_complex_list/android/app/src/debug/AndroidManifest.xml
  examples/flutter_complex_list/android/app/src/main/res/values-night/styles.xml
  examples/flutter_complex_list/android/app/src/main/res/values/styles.xml
  examples/flutter_complex_list/android/app/src/profile/AndroidManifest.xml
  examples/flutter_complex_list/android/build.gradle
  examples/flutter_complex_list/android/gradle/wrapper/gradle-wrapper.properties
  examples/flutter_complex_list/ios/Runner.xcodeproj/project.pbxproj
  examples/flutter_complex_list/ios/Runner/Info.plist
  examples/flutter_complex_list/lib/app.dart
  examples/flutter_complex_list/lib/complex_list/cubit/complex_list_cubit.dart
  examples/flutter_complex_list/lib/complex_list/view/complex_list_page.dart
  examples/flutter_complex_list/lib/simple_bloc_observer.dart
  examples/flutter_complex_list/pubspec.yaml
  examples/flutter_complex_list/test/complex_list/cubit/complex_list_cubit_test.dart
  examples/flutter_complex_list/test/complex_list/view/complex_list_page_test.dart
Labels: chore

#3392 fix(bloc): remove unnecessary "async" from "Emitter.onEach"
  packages/bloc/lib/src/emitter.dart
Labels: bug, pkg:bloc

#3410 docs(sidebar): zh-cn updates
  docs/zh-cn/_sidebar.md
  docs/zh-cn/architecture.md
  docs/zh-cn/blocnamingconventions.md
  docs/zh-cn/blocvscodeextension.md
  docs/zh-cn/coreconcepts.md
Labels: documentation, translation

#3409 docs(coreconcepts): add pt-br translation
  docs/pt-br/_sidebar.md
  docs/pt-br/coreconcepts.md
Labels: documentation, translation

#3413 ci: use semantic_pull_request workflow
  .github/workflows/ci.yaml
Labels: ci
