Repository felangel/bloc, pull requests merged in 2022-11, with the labels that each got.

#3599 chore(flutter_firebase_login): update deps
  examples/flutter_firebase_login/analysis_options.yaml
  examples/flutter_firebase_login/packages/authentication_repository/analysis_options.yaml
  examples/flutter_firebase_login/packages/authentication_repository/pubspec.yaml
  examples/flutter_firebase_login/packages/cache/analysis_options.yaml
  examples/flutter_firebase_login/packages/cache/pubspec.yaml
  examples/flutter_firebase_login/packages/form_inputs/analysis_options.yaml
  examples/flutter_firebase_login/packages/form_inputs/pubspec.yaml
  examples/flutter_firebase_login/pubspec.yaml
Labels: example, dependency updates

#3553 docs: remove effective dart badges
  README.md
  docs/_coverpage.md
  docs/az/README.md
  docs/az/_coverpage.md
  docs/cs/README.md
  docs/cs/_coverpage.md
  docs/de-de/README.md
  docs/de-de/_coverpage.md
  docs/es/README.md
  docs/es/_coverpage.md
  docs/fr/README.md
  docs/fr/_coverpage.md
  docs/jp/README.md
  docs/jp/_coverpage.md
  docs/ko-kr/README.md
  docs/ko-kr/_coverpage.md
  docs/pt-br/README.md
  docs/pt-br/_coverpage.md
  docs/ru/README.md
  docs/ru/_coverpage.md
  docs/zh-cn/README.md
  docs/zh-cn/_coverpage.md
  packages/angular_bloc/README.md
  packages/bloc/README.md
  packages/bloc_concurrency/README.md
  packages/bloc_test/README.md
  packages/bloc_tools/README.md
  packages/flutter_bloc/README.md
  packages/hydrated_bloc/README.md
  packages/replay_bloc/README.md
Labels: chore

#3603 chore(hydrated_bloc): upgrade to mocktail ^0.3.0
  packages/hydrated_bloc/pubspec.yaml
Labels: chore, pkg:hydrated_bloc, dependency updates

#3604 docs(hydrated_bloc): add testing section to README
  packages/hydrated_bloc/README.md
Labels: documentation, pkg:hydrated_bloc

#3605 test(flutter_weather): minor improvement to weather_page_test.dart
  examples/flutter_weather/test/weather/view/weather_page_test.dart
Labels: example

#3607 ci: upgrade actions
  .github/workflows/angular_bloc.yaml
  .github/workflows/angular_dart_examples.yaml
  .github/workflows/bloc.yaml
  .github/workflows/bloc_concurrency.yaml
  .github/workflows/bloc_test.yaml
  .github/workflows/bloc_tools.yaml
  .github/workflows/docs.yaml
  .github/workflows/flutter_bloc.yaml
  .github/workflows/flutter_examples.yaml
  .github/workflows/hydrated_bloc.yaml
  .github/workflows/replay_bloc.yaml
Labels: ci

#3606 chore(hydrated_bloc): v9.0.0
  packages/hydrated_bloc/CHANGELOG.md
  packages/hydrated_bloc/example/pubspec.yaml
  packages/hydrated_bloc/example/pubspec_overrides.yaml
  packages/hydrated_bloc/pubspec.yaml
Labels: release candidate, chore, pkg:hydrated_bloc

#3609 docs(migration): add hydrated_bloc v9.0.0 guide
  docs/migration.md
Labels: documentation

#3611 docs: bump to hydrated_bloc 9.0.0 in update-pubspec script
  docs/update-pubspec.js
Labels: documentation

#3613 docs(migration): fix hydrated_bloc v9.0.0 snippet
  docs/migration.md
Labels: documentation

#3615 chore(flutter_weather): upgrade to hydrated_bloc v9.0.0
  examples/flutter_weather/pubspec.yaml
  examples/flutter_weather/pubspec_overrides.yaml
Labels: example, dependency updates

#3617 docs(migration): add hydrated_bloc v9.0.0 translation (pt-br)
  docs/pt-br/migration.md
Labels: translation

#3619 docs(sponsors): add netguru
  README.md
  docs/_coverpage.md
  docs/az/_coverpage.md
  docs/cs/_coverpage.md
  docs/de-de/_coverpage.md
  docs/es/_coverpage.md
  docs/fr/_coverpage.md
  docs/jp/_coverpage.md
  docs/ko-kr/_coverpage.md
  docs/pt-br/_coverpage.md
  docs/ru/_coverpage.md
  docs/zh-cn/_coverpage.md
  packages/angular_bloc/README.md
  packages/bloc/README.md
  packages/bloc_concurrency/README.md
  packages/bloc_test/README.md
  packages/flutter_bloc/README.md
  packages/hydrated_bloc/README.md
  packages/replay_bloc/README.md
Labels: documentation, chore

#3630 refactor(flutter_login): make internal events private and use Dart 2.18
  examples/flutter_login/analysis_options.yaml
  examples/flutter_login/ios/Flutter/AppFrameworkInfo.plist
  examples/flutter_login/ios/Runner.xcodeproj/project.pbxproj
  examples/flutter_login/lib/authentication/bloc/authentication_bloc.dart
  examples/flutter_login/lib/authentication/bloc/authentication_event.dart
  examples/flutter_login/lib/login/models/password.dart
  examples/flutter_login/lib/login/models/username.dart
  examples/flutter_login/packages/authentication_repository/analysis_options.yaml
  examples/flutter_login/packages/authentication_repository/pubspec.yaml
  examples/flutter_login/packages/user_repository/analysis_options.yaml
  examples/flutter_login/packages/user_repository/pubspec.yaml
  examples/flutter_login/pubspec.yaml
  examples/flutter_login/test/authentication/authentication_bloc_test.dart
  examples/flutter_login/test/authentication/authentication_event_test.dart
Labels: example, refactor

#3628 docs: [KR][Architecture][Data Layer][Repository] Remove duplicated lines.
  docs/ko-kr/architecture.md
Labels: translation

#3632 refactor(flutter_firebase_login): make internal events private
  examples/flutter_firebase_login/ios/Podfile
  examples/flutter_firebase_login/lib/app/bloc/app_bloc.dart
  examples/flutter_firebase_login/lib/app/bloc/app_event.dart
  examples/flutter_firebase_login/lib/home/view/home_page.dart
  examples/flutter_firebase_login/packages/authentication_repository/lib/src/authentication_repository.dart
  examples/flutter_firebase_login/packages/authentication_repository/pubspec.yaml
  examples/flutter_firebase_login/packages/authentication_repository/test/authentication_repository_test.dart
  examples/flutter_firebase_login/pubspec.yaml
  examples/flutter_firebase_login/test/app/bloc/app_event_test.dart
  examples/flutter_firebase_login/test/home/view/home_page_test.dart
  examples/flutter_firebase_login/test/login/cubit/login_cubit_test.dart
  examples/flutter_firebase_login/test/sign_up/cubit/sign_up_cubit_test.dart
Labels: example, refactor

#3633 docs(faqs): adding events within a bloc
  docs/faqs.md
Labels: documentation
