Repository felangel/bloc, pull requests merged in 2022-10, with the labels that each got.

#3565 docs(flutter_todos): update very_good_cli commands in tutorial
  docs/fluttertodostutorial.md
Labels: example, documentation

#3568 fix(vscode): rename element to bloc in context.select snippet
  extensions/vscode/snippets/flutter_bloc.json
Labels: bug, extension

#3570 chore(vscode): v6.6.2
  extensions/vscode/CHANGELOG.md
  extensions/vscode/package-lock.json
  extensions/vscode/package.json
Labels: release candidate, extension, chore

#3587 ci: retain original build job
  .github/workflows/ci.yaml
Labels: ci

#3588 ci: fix broken build badge
  .github/workflows/build.yaml
Labels: ci
