Repository felangel/bloc, pull requests merged in 2022-01, with the labels that each got.

#3125 docs: update VGV sponsors logo
  README.md
  docs/_coverpage.md
  docs/assets/vgv_logo_transparent.png
  docs/az/README.md
  docs/az/_coverpage.md
  docs/cs/README.md
  docs/cs/_coverpage.md
  docs/de-de/README.md
  docs/de-de/_coverpage.md
  docs/es/README.md
  docs/es/_coverpage.md
  docs/fr/README.md
  docs/fr/_coverpage.md
  docs/jp/README.md
  docs/jp/_coverpage.md
  docs/ko-kr/README.md
  docs/ko-kr/_coverpage.md
  docs/pt-br/README.md
  docs/pt-br/_coverpage.md
  docs/ru/README.md
  docs/ru/_coverpage.md
  docs/zh-cn/README.md
  docs/zh-cn/_coverpage.md
  packages/angular_bloc/README.md
  packages/bloc/README.md
  packages/bloc_concurrency/README.md
  packages/bloc_test/README.md
  packages/flutter_bloc/README.md
  packages/hydrated_bloc/README.md
  packages/replay_bloc/README.md
Labels: documentation

#3127 feat(vscode): v6.4.0
  extensions/vscode/CHANGELOG.md
  extensions/vscode/README.md
  extensions/vscode/package.json
  extensions/vscode/snippets/bloc.json
  extensions/vscode/snippets/freezed_bloc.json
  extensions/vscode/src/commands/new-bloc.command.ts
  extensions/vscode/src/commands/new-cubit.command.ts
  extensions/vscode/src/utils/get-template-setting.ts
Labels: enhancement, release candidate, extension

#3132 refactor(flutter_counter): remove unnecessary IntegrationTestWidgetsFlutterBinding
  examples/flutter_counter/integration_test/app_test.dart
Labels: example, refactor

#3133 docs(fluttertodostutorial): use correct ascii character in `--recursive`
  docs/fluttertodostutorial.md
Labels: documentation

#3136 chore: update GetStream utm tags
  README.md
  docs/_coverpage.md
  docs/az/README.md
  docs/az/_coverpage.md
  docs/cs/README.md
  docs/cs/_coverpage.md
  docs/de-de/README.md
  docs/de-de/_coverpage.md
  docs/es/README.md
  docs/es/_coverpage.md
  docs/fr/README.md
  docs/fr/_coverpage.md
  docs/jp/README.md
  docs/jp/_coverpage.md
  docs/ko-kr/README.md
  docs/ko-kr/_coverpage.md
  docs/pt-br/README.md
  docs/pt-br/_coverpage.md
  docs/ru/README.md
  docs/ru/_coverpage.md
  docs/zh-cn/README.md
  docs/zh-cn/_coverpage.md
  packages/angular_bloc/README.md
  packages/bloc/README.md
  packages/bloc_concurrency/README.md
  packages/bloc_test/README.md
  packages/flutter_bloc/README.md
  packages/hydrated_bloc/README.md
  packages/replay_bloc/README.md
Labels: chore

#3139 docs(fluttertodostutorial): Fix typo (Respository -> Repository)
  docs/_snippets/flutter_todos_tutorial/images/todos_architecture_light.png
  docs/fluttertodostutorial.md
Labels: documentation

#3144 docs(coreconcepts): translation improvements (zh-cn)
  docs/zh-cn/coreconcepts.md
Labels: documentation, translation

#3151 docs(fluttertodostutorial): fix --desc typo in code snippets
  docs/fluttertodostutorial.md
Labels: documentation

#3153 docs(fluttertimertutorial): add zh-cn translations
  docs/zh-cn/fluttertimertutorial.md
Labels: translation

#3154 docs(fluttertimertutorial): add zh-cn translation to sidebar
  docs/zh-cn/_sidebar.md
  docs/zh-cn/fluttertimertutorial.md
Labels: documentation

#3156 chore(bloc_tools): upgrade to mason 0.1.0-dev.4
  packages/bloc_tools/pubspec.yaml
Labels: chore, dependency updates, pkg:bloc_tools

#3167 docs(bloc): Included missing slash in doc comment
  packages/bloc/lib/src/emitter.dart
Labels: documentation, pkg:bloc

#3158 zh-cn translation
  docs/zh-cn/angularcountertutorial.md
  docs/zh-cn/blocintellijextension.md
Labels: translation

#3173 update zh-cn translation faqs.md
  docs/zh-cn/faqs.md
  docs/zh-cn/flutterbloccoreconcepts.md
Labels: translation
