Repository felangel/bloc, pull requests merged in 2023-03, with the labels that each got.

#3762 fix(vscode): wrap with interpolation
  extensions/vscode/package.json
  extensions/vscode/src/utils/wrap-with.ts
Labels: bug

#3763 chore(vscode): v6.6.3
  extensions/vscode/.vscode/launch.json
  extensions/vscode/CHANGELOG.md
  extensions/vscode/README.md
  extensions/vscode/package-lock.json
  extensions/vscode/package.json
  extensions/vscode/tsconfig.json
Labels: release candidate, extension, chore

#3767 docs: remove discontinued package from README
  README.md
Labels: documentation

#3751 docs(architecture): improve `blocs_presentation.dart.md` snippet
  docs/_snippets/architecture/blocs_presentation.dart.md
Labels: documentation

#3774 chore: update casing in articles section of README
  README.md
Labels: chore
