Repository felangel/bloc, pull requests merged in 2024-10, with the labels that each got.

#4258 feat(intellij): upgrade platform version to 2022.3/Java 17
  extensions/intellij/intellij_generator_plugin/.gitignore
  extensions/intellij/intellij_generator_plugin/build.gradle
  extensions/intellij/intellij_generator_plugin/gradle.properties
  extensions/intellij/intellij_generator_plugin/gradle/wrapper/gradle-wrapper.properties
  extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/action/GenerateBlocAction.kt
  extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/action/GenerateCubitAction.kt
  extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/action/GenerateEquatablePropsAction.kt
  extensions/intellij/intellij_generator_plugin/src/main/resources/META-INF/plugin.xml
Labels: bug, enhancement, extension

#4259 chore(angular_bloc): v10.0.0-dev.4
  packages/angular_bloc/CHANGELOG.md
  packages/angular_bloc/README.md
  packages/angular_bloc/pubspec.yaml
Labels: release candidate, chore

#4267 docs: fix typo in ko/bloc-concepts.mdx
  docs/src/content/docs/ko/bloc-concepts.mdx
Labels: documentation, translation

#4269 docs(bloc-concepts): add Portuguese translation
  docs/src/content/docs/pt-br/bloc-concepts.mdx
Labels: translation
