Repository felangel/bloc, pull requests merged in 2024-06, with the labels that each got.

#4184 doc: fix gallery images
  packages/flutter_bloc/README.md
Labels: documentation

#4189 chore(flutter_bloc): v8.1.6
  packages/flutter_bloc/CHANGELOG.md
  packages/flutter_bloc/pubspec.yaml
Labels: release candidate, pkg:flutter_bloc, chore

#4190 refactor: add `missing_code_block_language_in_doc_comment` to `analysis_options.yaml`
  analysis_options.yaml
Labels: refactor
