Repository felangel/bloc, pull requests merged in 2024-04, with the labels that each got.

#4128 docs: add `zh-cn/flutter-bloc-concepts.mdx`
  docs/src/content/docs/zh-cn/flutter-bloc-concepts.mdx
Labels: translation

#4132 docs: add `pt-br/why-bloc.mdx`
  docs/src/content/docs/pt-br/why-bloc.mdx
Labels: translation

#4137 refactor(bloc)!: remove deprecated `BlocOverrides`
  packages/bloc/lib/src/bloc.dart
  packages/bloc/lib/src/bloc_base.dart
  packages/bloc/lib/src/bloc_overrides.dart
  packages/bloc/test/bloc_event_transformer_test_legacy.dart
  packages/bloc/test/bloc_overrides_test.dart
  packages/bloc/test/bloc_test_legacy.dart
  packages/bloc/test/cubit_test_legacy.dart
  packages/bloc_test/lib/src/bloc_test.dart
  packages/replay_bloc/lib/src/replay_bloc.dart
Labels: pkg:bloc, breaking change, refactor

#4143 docs(SponsorsGrid): open sponsors links in new tab
  docs/src/components/landing/SponsorsGrid.astro
Labels: documentation

#4147 ci: upgrade to `very_good_coverage@v3`
  .github/actions/dart_package/action.yaml
  .github/actions/flutter_package/action.yaml
Labels: ci

#4145 docs: fix typo in `architecture.mdx`
  docs/src/content/docs/architecture.mdx
Labels: documentation

#4150 docs: add automatic header anchor links
  docs/astro.config.mjs
  docs/package-lock.json
  docs/package.json
  docs/plugins/rehype-autolink.ts
  docs/src/components/starlight/MarkdownContent.astro
Labels: documentation

#4148 docs: use optimized astro `Image` in `SponsorsGrid.astro`
  docs/src/components/landing/SponsorsGrid.astro
Labels: documentation

#4153 docs: add trailing slash to introduction section links
  docs/astro.config.mjs
Labels: documentation

#4157 refactor(flutter_todos): add `close` to `TodosApi`
  examples/flutter_todos/packages/local_storage_todos_api/lib/src/local_storage_todos_api.dart
  examples/flutter_todos/packages/local_storage_todos_api/test/local_storage_todos_api_test.dart
  examples/flutter_todos/packages/todos_api/lib/src/todos_api.dart
Labels: example, refactor

#4160 docs: add `ko` translations for introduction sections
  docs/astro.config.mjs
  docs/src/content/docs/ko/architecture.mdx
  docs/src/content/docs/ko/bloc-concepts.mdx
  docs/src/content/docs/ko/faqs.mdx
  docs/src/content/docs/ko/flutter-bloc-concepts.mdx
  docs/src/content/docs/ko/getting-started.mdx
  docs/src/content/docs/ko/index.mdx
  docs/src/content/docs/ko/naming-conventions.mdx
  docs/src/content/docs/ko/testing.mdx
  docs/src/content/docs/ko/why-bloc.mdx
Labels: translation

#4155 docs: mention `stream_transform` and `rxdart` in `bloc-concepts.mdx`
  docs/src/content/docs/bloc-concepts.mdx
Labels: documentation
