Repository felangel/bloc, pull requests merged in 2024-09, with the labels that each got.

#4201 docs: add section on modeling state
  docs/astro.config.mjs
  docs/src/components/modeling-state/ConcreteClassAndStatusEnumSnippet.astro
  docs/src/components/modeling-state/SealedClassAndSubclassesSnippet.astro
  docs/src/content/docs/modeling-state.mdx
Labels: documentation

#4233 docs(flutter_infinite_list): minor tutorial updates
  docs/src/content/docs/tutorials/flutter-infinite-list.mdx
Labels: documentation

#4234 refactor(flutter_infinite_list): simplify `PostFetched` event handler
  examples/flutter_infinite_list/lib/posts/bloc/post_bloc.dart
Labels: example, refactor

#4242 docs: add zh-cn/index.mdx and the first 3 pages
  docs/astro.config.mjs
  docs/src/content/docs/zh-cn/bloc-concepts.mdx
  docs/src/content/docs/zh-cn/flutter-bloc-concepts.mdx
  docs/src/content/docs/zh-cn/getting-started.mdx
  docs/src/content/docs/zh-cn/index.mdx
  docs/src/content/docs/zh-cn/why-bloc.mdx
Labels: translation

#4244 docs(zh-cn): add flutter-counter.mdx
  docs/src/content/docs/zh-cn/tutorials/flutter-counter.mdx
Labels: translation
