Repository felangel/bloc, pull requests merged in 2024-05, with the labels that each got.

#4163 docs: add `de/index.mdx`
  docs/src/content/docs/de/index.mdx
Labels: translation

#4168 chore(intellij): v4.0.1
  extensions/intellij/intellij_generator_plugin/build.gradle
  extensions/intellij/intellij_generator_plugin/src/main/resources/META-INF/plugin.xml
Labels: release candidate, extension

#4103 docs: add `ar/index.mdx` and `ar/getting-started.mdx`
  docs/src/content/docs/ar/getting-started.mdx
Labels: translation

#4170 docs: add `fa/index.mdx`, `fa/getting-started.mdx`, and `fa/why-bloc.mdx`
  docs/astro.config.mjs
  docs/src/content/docs/fa/getting-started.mdx
  docs/src/content/docs/fa/index.mdx
  docs/src/content/docs/fa/why-bloc.mdx
Labels: translation

#4177 docs: set text direction to `rtl` for persian and arabic
  docs/astro.config.mjs
Labels: documentation, translation

#4179 docs: Add persian(fa) translation
  docs/src/content/docs/fa/naming-conventions.mdx
  docs/src/content/docs/fa/testing.mdx
  docs/src/content/docs/fa/why-bloc.mdx
Labels: translation
